### ISSUE TITLE
Which method to call to execute this program?

### ISSUE THREAD

**Issue by Hack-NLP** [cheind/py-motmetrics#1]
how to pass GT, Test files to this app?
can you explain what are files in etc/data/iotest and how are these different from etc/data/TUD-Campus?
can you give examples for above in your documentation!

Thanks

**Comment by cheind** [comment]
Hi, sorry for being late. Seems like you figured it out?

**Comment by 404hasbeenfound** [comment]
@cheind I have the same question too, can you give a example for this documentation ? for example, i have a test text named MOT16-14.txt, and i have the official text named MOT16-14/gt.txt, how can i pass this to your app? I have test your TUD-Campus/gt/gt.txt and your gt text, like the later image, but the result is not like a result. And the structure is like that,
~/TUD-Campus/gt/gt.txt
~/TUD-Campus/test.txt

(zmh) adminroot@adminroot:~/zmh/py-motmetrics-master/motmetrics/apps$ python eval_motchallenge.py /home/adminroot/zmh/py-motmetrics-master/motmetrics/data/TUD-Campus/gt  /home/adminroot/zmh/py-motmetrics-master/motmetrics/data/TUD-Campus
11:37:32 INFO - Found 0 groundtruths and 1 test files.
11:37:32 INFO - Available LAP solvers ['scipy']
11:37:32 INFO - Default LAP solver 'scipy'
11:37:32 INFO - Loading files.
11:37:32 WARNING - No ground truth for test, skipping.
11:37:32 INFO - Running metrics
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:378: RuntimeWarning: invalid value encountered in double_scalars
  return 2 * idtp / (num_objects + num_predictions)
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:370: RuntimeWarning: invalid value encountered in double_scalars
  return idtp / (idtp + idfp)
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:374: RuntimeWarning: invalid value encountered in double_scalars
  return idtp / (idtp + idfn)
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:302: RuntimeWarning: invalid value encountered in long_scalars
  return num_detections / num_objects
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:298: RuntimeWarning: invalid value encountered in long_scalars
  return num_detections / (num_false_positives + num_detections)
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:294: RuntimeWarning: invalid value encountered in long_scalars
  return 1. - (num_misses + num_switches + num_false_positives) / num_objects
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:290: RuntimeWarning: invalid value encountered in double_scalars
  return df.noraw['D'].sum() / num_detections
        IDF1  IDP  IDR Rcll Prcn GT MT PT ML FP FN IDs  FM MOTA MOTP
OVERALL nan% nan% nan% nan% nan%  0  0  0  0  0  0   0   0 nan%  nan
11:37:32 INFO - Completed

**Comment by 404hasbeenfound** [comment]
@cheind I have the same question too, can you give a example for this documentation ? for example, i have a test text named MOT16-14.txt, and i have the official text named MOT16-14/gt.txt, how can i pass this to your app? I have test your TUD-Campus/gt/gt.txt and your gt text, like the later image, but the result is not like a result. And the structure is like that,
~/TUD-Campus/gt/gt.txt
~/TUD-Campus/test.txt

(zmh) adminroot@adminroot:~/zmh/master$ python eval_motchallenge.py /home/adminroot/zmh/py-motmetrics-master/motmetrics/data/TUD-Campus /home/adminroot/zmh/py-motmetrics-master/motmetrics/data/TUD-Campus    11:21:39 INFO - Found 1 groundtruths and 1 test files.
11:21:39 INFO - Available LAP solvers ['scipy']
11:21:39 INFO - Default LAP solver 'scipy'
11:21:39 INFO - Loading files.
11:21:39 INFO - Comparing MOT16-11...
11:21:40 INFO - Running metrics
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:370: RuntimeWarning: invalid value encountered in double_scalars
  return idtp / (idtp + idfp)
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:298: RuntimeWarning: invalid value encountered in long_scalars
  return num_detections / (num_false_positives + num_detections)
/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/metrics.py:290: RuntimeWarning: invalid value encountered in double_scalars
  return df.noraw['D'].sum() / num_detections
         IDF1  IDP  IDR Rcll Prcn GT MT PT ML FP   FN IDs  FM MOTA MOTP
MOT16-11 0.0% nan% 0.0% 0.0% nan% 69  0  0 69  0 9174   0   0 0.0%  nan
OVERALL  0.0% nan% 0.0% 0.0% nan% 69  0  0 69  0 9174   0   0 0.0%  nan
11:21:42 INFO - Completed
