### ISSUE TITLE
nan values still present

### ISSUE THREAD

**Issue by christosavg** [cheind/py-motmetrics#10]
Hi and thank you for your work. 
I've been facing `'the label [nan] is not in the [index]'` when executing the example.py script.

The error is also present when trying to test my data on the ground truth, using 
`python -m motmetrics.apps.eval_motchallenge`

It seems to occur at:
File "/usr/local/lib/python3.5/dist-packages/motmetrics/metrics.py", line 335, in id_global_assignment
    df_o = df.loc[o, 'D'].dropna()

Is this a possible pandas bug not removing NaN values? Perhaps I'm doing something wrong.
Thanks a lot.

Edit: After scrolling through the other issues again, I found [EchoTheory](https://github.com/cheind/py-motmetrics/issues/9#issuecomment-391442686)'s answer. Thankfully I'm building in a docker environment so I'd strongly suggest you'd do the same (or use a virtual env)

**Comment by cheind** [comment]
Hi Chris, could you provide a minimal example that reproduces the issue?

**Comment by cheind** [comment]
Could you please verify that the latest develop is now working with most recent pandas?
