### ISSUE TITLE
error with cuda 10.1

### ISSUE THREAD

**Issue by resplendent-star** [cheind/py-motmetrics#100]
ubuntu18.04  cuda 10.1 python 3.7 
use conda to install  out put error:
------------------------------------------------------------------------------------------------------------------------
Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1

**Comment by cheind** [comment]
Hi, I'm not sure how this could be caused by mometrics. Do you have full error logs? I'm usually not installing through conda (there is no official support for a py-motmetrics conda package), please try to follow the instructions given [here](https://github.com/cheind/py-motmetrics#installation).

**Comment by resplendent-star** [comment]
> Hi, I'm not sure how this could be caused by mometrics. Do you have full error logs? I'm usually not installing through conda (there is no official support for a py-motmetrics conda package), please try to follow the instructions given [here](https://github.com/cheind/py-motmetrics#installation).

--------------------------------------------------------------
 conda install motmetrics
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1

**Comment by Shiyong2019** [comment]
@resplendent-star @cheind ，
Hi，I have the same problem.  Do you have any suggestion?  Thanks!

My error logs: 
(py3envs) UU@XXX:~$ conda install -c loopbio motmetrics 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==9.0=0
  - feature:|@/linux-64::__cuda==9.0=0

Your installed CUDA driver is: 9.0

**Comment by cheind** [comment]
As mentioned above, I'm not actively maintaining a conda package. Please use `pip` to install **py-motmetrics** as explained [here](https://github.com/cheind/py-motmetrics#installation).

**Comment by cheind** [comment]
I've reached out to `loopbio`, a company, who seems to have created a conda package.  Maybe they are able to resolve your issues by joining our discussion.

**Comment by resplendent-star** [comment]
> 如上所述，我没有积极维护conda软件包。请按[此处所述](https://github.com/cheind/py-motmetrics#installation)使用`pip`来安装**py-motmetrics**。[](https://github.com/cheind/py-motmetrics#installation)

thanks

**Comment by resplendent-star** [comment]
> 如上所述，我没有积极维护conda软件包。请按[此处所述](https://github.com/cheind/py-motmetrics#installation)使用`pip`来安装**py-motmetrics**。[](https://github.com/cheind/py-motmetrics#installation)

it  works,thank you  very  much

**Comment by resplendent-star** [comment]
> @ resplendent-star @cheind，
> 嗨，我有同样的问题。你有什么建议吗？谢谢！
> 
> 我的错误日志：
> （py3envs）UU @ XXX：〜$ conda install -c loopbio motmetrics
> 收集软件包元数据（current_repodata.json）：完成
> 求解环境：最初的冻结求解失败。使用灵活的解决方法重试。
> 解决环境：由于current_repodata.json中的repodata失败，将重试下一个repodata源。
> 收集程序包元数据（repodata.json）：完成
> 求解环境：最初的冻结求解失败。使用灵活的解决方法重试。
> 解决环境：
> 发现冲突！寻找不相容的套件。
> 这可能需要几分钟。按CTRL-C中止。
> 失败了
> 
> UnsatisfiableError：发现以下规格彼此不兼容：
> 格式输出：请求的程序包->可用版本发现以下规格与您的CUDA驱动程序不兼容：
> 
> * 功能：/ linux-64 :: __ cuda == 9.0 = 0
> * 功能：| @ / linux-64 :: __ cuda == 9.0 = 0
> 
> 您安装的CUDA驱动程序为：9.0

(3.8.1) lzw@resplendent-star:~/3d_lib/3d_lib_py/spconv$ pip install motmetrics

it will work
