### ISSUE TITLE
We get a negative result

### ISSUE THREAD

**Issue by ChenSi521** [cheind/py-motmetrics#103]
I used our validate dataset, but got a negative result.
mota: -6.2%
Can you tell me how to modify my gt.txt?

**Comment by jvlmdr** [comment]
While it is conventional to consider MOTA as a percentage, there is nothing inherently incorrect with a negative result for MOTA. Recall the definition `MOTA = 1 - (FN + FP + IDSW) / GT`. The number of false negatives and ID switches is bounded by the number of ground-truth boxes `FN + IDSW <= GT`. However, it is entirely possible for `FP + (FN + IDSW)` to exceed `GT`.

**Comment by ChenSi521** [comment]
@jvlmdr thanks!  I get it.

**Comment by jvlmdr** [comment]
Great!
