### ISSUE TITLE
What property (confidence, class, visibility) tells pymotmetrics when to diregard an entry during evaluation?

### ISSUE THREAD

**Issue by igygi** [cheind/py-motmetrics#106]
Hi, 

I am working on a custom dataset and generating my own groundtruth annotations. In line with this, I'd like to know what property in the groundtruth annotations should be adjusted to tell pymotmetrics to disregard an entry (e.g. due to occlusion). 

Is it confidence, class, or visibility? And what value setting should be used so that it is disregarded during evaluation? Thank you. 

Thanks.

**Comment by jvlmdr** [comment]
The util function for loading data in the MOT challenge format uses the "confidence" field and the `min_confidence` kwarg to ignore elements: https://github.com/cheind/py-motmetrics/blob/0a6b598d9c966b05c4317f051119948d9140d0e2/motmetrics/io.py#L93

**Comment by cheind** [comment]
Closing this question as resolved
