### ISSUE TITLE
MOTP is computed incorrectly

### ISSUE THREAD

**Issue by ningdez** [cheind/py-motmetrics#112]
The MOTP is incorrect when IoU is not set to be 0.5. For example,  when we set Iou to 0.3, the correct MOTP is  (1-motp), where motp is the ouput result.

**Comment by cheind** [comment]
Hey! The [Readme](https://github.com/cheind/py-motmetrics#motchallenge-compatibility) states

> Metric MOTP seems to be off. To convert compute (1 - MOTP) * 100. MOTChallenge benchmarks compute MOTP as percentage, while py-motmetrics sticks to the original definition of average distance over number of assigned objects [1].

Does this resolve your issue?

**Comment by ningdez** [comment]
> Hey! The [Readme](https://github.com/cheind/py-motmetrics#motchallenge-compatibility) states
> 
> > Metric MOTP seems to be off. To convert compute (1 - MOTP) * 100. MOTChallenge benchmarks compute MOTP as percentage, while py-motmetrics sticks to the original definition of average distance over number of assigned objects [1].
> 
> Does this resolve your issue?

Yes, I modify some code.
In the 174 line of evaluateTracking.py:
> "accs, analysis, names = compare_dataframes(gt, ts, args.log, 1- args.iou)" is modified to "accs, analysis, names = compare_dataframes(gt, ts, args.log, args.iou)"

In the 122 line of distances.py:
>  "dist = 1-iou" is modified to "dist = iou"

**Comment by ningdez** [comment]
> Hey! The [Readme](https://github.com/cheind/py-motmetrics#motchallenge-compatibility) states
> 
> > Metric MOTP seems to be off. To convert compute (1 - MOTP) * 100. MOTChallenge benchmarks compute MOTP as percentage, while py-motmetrics sticks to the original definition of average distance over number of assigned objects [1].
> 
> Does this resolve your issue?

Ok, I got it. Thanks.
