### ISSUE TITLE
how can I get the MOT metrics when using custom dataset(COCO or VOC format) as training set? 

### ISSUE THREAD

**Issue by Veronica1997** [cheind/py-motmetrics#119]
Should I convert the COCO or VOC format datasets to MOT format? 
Do you know how to convert?
Thanks a lot!

**Comment by cheind** [comment]
Hey, I believe I have seen this done before. Facebook research provides this code I guess:

https://github.com/facebookresearch/DetectAndTrack/

> [...] Since the datasets are represented using COCO conventions in Detectron code base, we need the COCO API to be able to read the train/test files. [...] Evaluation is performed using the official PoseTrack evaluation code, poseval, which uses py-motmetrics internally

**Comment by Veronica1997** [comment]
> Hey, I believe I have seen this done before. Facebook research provides this code I guess:
> 
> https://github.com/facebookresearch/DetectAndTrack/
> 
> > [...] Since the datasets are represented using COCO conventions in Detectron code base, we need the COCO API to be able to read the train/test files. [...] Evaluation is performed using the official PoseTrack evaluation code, poseval, which uses py-motmetrics internally

Thank you very much! It completely solved my problem! appreciate!

**Comment by cheind** [comment]
Great!
