### ISSUE TITLE
NaN MOTP and MOTA

### ISSUE THREAD

**Issue by osaki34** [cheind/py-motmetrics#12]
Hi my name is Olivier. I try to run py-motmetrics with spyder and i got an issue.

I don't know why but when i run Py-motmetrics this way    

`mh= mm.metrics.create()` 

` GroundTruth = mm.io.loadtxt("gt.txt")` 

` Test= mm.io.loadtxt("Test.txt")` 
` acc = mm.utils.compare_to_groundtruth(GroundTruth, Test)` 
` summary = mh.compute(
    acc,
    metrics=[
        "num_frames",
        "mostly_tracked",
        "partially_tracked",
        "mostly_lost",
        "num_fragmentations",
        "mota",
        "motp",
        "num_detections",
        'num_matches',
        'num_switches',
    ],
    name="acc",
)` 
` strsummary = mm.io.render_summary(
    summary, formatters=mh.formatters, namemap=mm.io.motchallenge_metric_names
)` 
` print(strsummary)` 

I got this message 
   `  num_frames MT PT ML  FM MOTA MOTP num_detections num_matches IDs
acc        101  1  0  1   0 0.0%  nan              0           0   0
C:\Users\osacchi\AppData\Local\Continuum\anaconda3\lib\site-packages\motmetrics\metrics.py:290: RuntimeWarning: invalid value encountered in double_scalars
  return df.noraw['D'].sum() / num_detections` 

When i use data like "MOT17DetLabels/train/MOT17-02/gt/gt.txt" and "res/MOT17Det/DPM/data/MOT17-02.txt" there is no problem but when i use my data i got this error. 
Normaly my data while be of the same format than MOTchallenge data (same dtypes, same number of columns etc, etc)

my dataframe are like that : 
Ground truth (create by me): 

           
` X     Y      Width     Height       Confidence  ClassId  Visibility`
` FrameId Id  `                                                         
` 1       -1     0     0    150     2               0        7         1.0` 
` 2       -1     9     9    150    2              0        7         1.0` 
` 3       -1    19    19    150     2               0        7         1.0` 
` 4       -1    29    29    150     2              0        7         1.0` 
` 5       -1    39    39    150     2               0        7         1.0` 
` 6       -1    50    50    150     2               0        7         1.0` 
` 7       -1    60    60    150    2               0        7         1.0` 
` 8       -1    70    70    150     2               0        7         1.0` 
` 9       -1    80    80    150     2               0        7         1.0` 
` 10      -1    91    91    150     2               0        7         1.0` 
` 11      -1   101   101    150     2               0        7         1.0` 

and Test is like that : 

`                      X            Y                    Width Height  Confidence ClassId  Visibility`
`FrameId Id `                                                    
`1       -1     0.000000     0.000000    150   10    2    -1   -1   -1`
`2       -1     1.000000     1.000000    150   10    2     -1   -1   -1`
`3       -1     2.000000     2.000000     150   10    2     -1  -1    -1`
`4       -1     3.000000     3.000000     150   10    2             -1         -1          -1`
`5       -1     4.000000     4.000000     150   10   2             -1         -1          -1`
`6       -1    50.199972    50.200520     150   10    2             -1         -1          -1`
`7       -1    60.439959    60.439959     150   10    2             -1         -1          -1`
`8       -1    70.680017    70.680007     150   10    2             -1         -1          -1`
`9       -1    80.919994    80.919998     150   10    2             -1         -1          -1`
`10      -1    91.160002    91.160001     150   10    2             -1         -1          -1`
`11      -1   101.399999   101.400000     150   10    2             -1         -1          -1`

If I try to use Py-motmetrics on Test with Test or GroundTruth on GroundTruth it works.

   `num_frames MT PT ML  FM   MOTA  MOTP num_detections num_matches IDs`
`acc        101  1  0  0   0 100.0% 0.000            101         101   0`

Do you have any idea?

Thanks in advance and sorry for my horrible english.

**Comment by cheind** [comment]
Hi Oliver,

not sure what's causing this, but you might want to have a look at open #10 , #9. There is a chance that it is related, but in your case it seems more likely that something is off with your data. Could you try reducing number of objects / pred to a minimum reproducable test case?

**Comment by osaki34** [comment]
Hi, actually this is what i'm trying to do with the MOTchallenge dataset. I also think there is a problem with my data. Thanks for your answer if i find a solution i'll comment you back.

**Comment by cheind** [comment]
ok, reopen if necessary.
