### ISSUE TITLE
How to Obtain Precise True Positive TP

### ISSUE THREAD

**Issue by takehiro-code** [cheind/py-motmetrics#141]
How do we get the true positive TP? I know I can get it from Precision or recall since
Precision = TP/(TP+FP) --> get TP or
Recall = TP/(TP+FN) --> get TP
I got different TP values and I guess it is due to the limited decimal places in precision or recall.
Is there any way to get a precise TP value?

**Comment by jvlmdr** [comment]
The number of TP is available as "num_detections"
