### ISSUE TITLE
PyPI Update?

### ISSUE THREAD

**Issue by sampepose** [cheind/py-motmetrics#148]
Hi, there hasn't been an update to PyPI since Feb 2020. Can you please send out a v1.2.1? I'd like to get the latest changes on master packaged up. Thanks!

**Comment by smidm** [comment]
I'm stressing on this. I'm running into a package conflict due to flake8 dependency in the 1.2.1 version on the PyPi that forces old version of importlib-metadata. Looking forward to the update!

**Comment by cheind** [comment]
fully understandable. In the mean-time, wouldn't adding git+https package to your requirements.txt (as described in the below link), also work?

https://github.com/cheind/py-motmetrics#installation

**Comment by smidm** [comment]
In general yers, but it is not possible to put a package with git+https dependencies on PyPI. They forbid that. 

I want to move my package https://github.com/smidm/motutils on PyPI.

**Comment by cheind** [comment]
@smidm nice project! I hope to find a bit of time in the next week.

Hth!

**Comment by cheind** [comment]
@smidm 1.2.5 package uploaded. See if that works for you.

https://pypi.org/manage/project/motmetrics/release/1.2.5/

**Comment by cheind** [comment]
closing
