### ISSUE TITLE
track  points

### ISSUE THREAD

**Issue by CompliceU** [cheind/py-motmetrics#156]
@cheind Hello, thank you very much for your work, I now want to use him to measure my point tracking effect, not sure what I need to change

**Comment by cheind** [comment]
py-motmetrics basically works on distance matrices (groundtruth objects to predictions) per frame (see readme). These matrices are computed per default using the IoU metric, but can be anything you like (e.g. distances between points). See 

https://github.com/cheind/py-motmetrics#populating-the-accumulator
