### ISSUE TITLE
many 0 and nan return

### ISSUE THREAD

**Issue by taojake** [cheind/py-motmetrics#16]
Hi, i run my own data, it return many zero and nan, i sucess in TUD-Campus example.
my gt txt:
2,1,1702,246,31,61,1,-1,-1,-1
2,2,2351,313,39,77,1,-1,-1,-1
2,3,1745,191,24,57,1,-1,-1,-1
2,4,2199,175,25,60,1,-1,-1,-1
my test txt:
2,1,485.700000,267.020000,53.650000,76.000000,-1,-1,-1,-1
2,2,210.860000,172.800000,28.490000,56.980000,-1,-1,-1,-1
2,3,325.400000,106.000000,26.970000,65.000000,-1,-1,-1,-1
2,4,289.370000,231.810000,31.520000,59.140000,-1,-1,-1,-1
my res:
IDF1  IDP  IDR Rcll Prcn GT MT PT ML   FP   FN IDs  FM   MOTA MOTP
0.0% 0.0% 0.0% 0.0% 0.0% 31  0  0 31 5865 7734   0   0 -75.8%  nan
0.0% 0.0% 0.0% 0.0% 0.0% 31  0  0 31 5865 7734   0   0 -75.8%  nan
and has runtime warming:
/python3.5/site-packages/motmetrics/metrics.py:290: RuntimeWarning: invalid value encountered in double_scalars  return df.noraw['D'].sum() / num_detections

what's problem do i meet?
Thanks.

**Comment by cheind** [comment]
just from a quick glimpse, it seems your bounding boxes do not overlap at all.

**Comment by taojake** [comment]
@cheind thanks reply, i have figured out, your job is great.

**Comment by 404hasbeenfound** [comment]
@taojake how you figure it out? i have the same confusion in my project.
