### ISSUE TITLE
mh.compute_many with generate_overall seems to freeze

### ISSUE THREAD

**Issue by madhawav** [cheind/py-motmetrics#17]
Hi all,
I called mh.compute_many(generate_overall=True) with data on 7 input videos (in MOT training set) and the call seems to get stuck in a never-ending loop. It has been about 16 hours since I made the call but still no result. 

```python
filtered_summary = mh.compute_many(
            [x[1] for x in filtered_results], 
            metrics=mm.metrics.motchallenge_metrics, 
            names=[x[0] for x in filtered_results],
            generate_overall=True
        )
```
I got results in like 20 minutes when the generate_overall option is not set.

Is there any technique to make this operation faster?
Thanks in advance

**Comment by cheind** [comment]
That's interesting. When `generate_overall` is set, the events from all instances are merged an metrics are computed on the merged events. This can be seen here

https://github.com/cheind/py-motmetrics/blob/master/motmetrics/metrics.py#L187

Which lap-solver backend are you using?

One way to reduce computation time is to generate the summarized statististcs based on weighted average of individual video metrics. This hasn't been implemented as it is not clear what the weights should be (number of frames, number of objects...). You could get the number of frames through `num_frames`.

**Comment by madhawav** [comment]
Thanks for replying @cheind. I have not changed the default solver. (I think it is using Scipy).

Usually how long should it take in your opinion? (Without generate_overall, the process completed in 20 minutes and I am using 7 videos). And is there any way to calculate the overalls using individual videos results? 

The process is still going on in my machine.

**Comment by cheind** [comment]
you might want to try py-lapsolver https://github.com/cheind/py-lapsolver which is 2-3 times faster than scipy on relevant cases.

**Comment by madhawav** [comment]
@cheind I got the results after about 21 hours. So it's not stuck but very long to process. I should find a faster method to get the results. So, I will try out py-lapsolver also and let you know.

**Comment by cheind** [comment]
great it didn't get stuck! Let me know if py-lapsolver helps, otherwise you might want to compute the overall stats yourself.

**Comment by madhawav** [comment]
Hi,
I actually managed to finish my experiments without using py-lapsolver. If the time permits, I will re-run the code with py-lapsolver and share the timing results here. 

Thank you for your help and sorry for my delay in response.
Cheers!

**Comment by cheind** [comment]
Ok, reopen if needed.

**Comment by cheind** [comment]
sorry, was already closed ;)
