### ISSUE TITLE
FN and FP numbers are way off

### ISSUE THREAD

**Issue by tonmoyborah** [cheind/py-motmetrics#18]
Hi @cheind , great work with the repo and all the help.
When I try this on my own tracking algorithm and my own dataset (in MOT Challenge format), I get quite weird values.

        IDF1  IDP  IDR Rcll Prcn GT MT PT ML  FP IDs  FM   MOTA   MOTP num_objects num_predictions  FN
test    3.6% 3.6% 3.6% 5.4% 5.5%  3  0  0  3 467   1   2 -88.7% 61.671         497             494 470
OVERALL 3.6% 3.6% 3.6% 5.4% 5.5%  3  0  0  3 467   1   2 -88.7% 61.671         497             494 470

Sorry for my formatting skills but the problem is that the MOTA is negative, because the number of FP(467) + FN(470) is greater than the total objects(497) which should not be possible. I think the scores are done after graph matching so it is not necessary that the tracker assign exactly the same id as the gt, is it? Also, any other factors I need to take care of in my gt and ts txt files?
Thank you.
My gt and ts files are in [here](https://gist.github.com/tonmoyborah/17259e40482492b68ae10120caa8e1f4)

**Comment by tonmoyborah** [comment]
Its an id like any other. So basically we shouldn't use negative numbers
for id? I am using deep sort for tracking over some detection algorithms.

**Comment by tonmoyborah** [comment]
Hi @cheind 
I changed the id from -1 to 1000, now the numbers are different but similarly weird. The IDF1 scores are 0% and MOTA is -39.5%.
How is the id influencing these scores. I thought the label value had nothing to do with the score as assignments are made by bipartite graph matching. Which part of the code is effected by the id value? And is there a id to id matching going on? For eg, if my gt has set and id x to an object, should my tracker predict its id as x too? 
Thanks for the prompt replies.

**Comment by tonmoyborah** [comment]
When I print acc.events, the Distance column is always NaN. Note that when I visualise my tracker output, the tracker is doing a fine job

**Comment by tonmoyborah** [comment]
@cheind 
After some finding, I ended up getting decent results after changing [this](https://github.com/cheind/py-motmetrics/blob/125304fb53495de8a43f2768bf90eb932c4a87bb/motmetrics/distances.py#L103) line. Imo this should be `isect_a/union_a` and not `1 - isect_a/union_a`. What do you think?

**Comment by MuadDev** [comment]
@tonmoyborah I don't agree. That code computes the cost, where a higher cost means a lower likelyhood to form a match. When `isect_a/union_a is` high, this means there is a good overlap. And when there is a good overlap we want the cost to be low, not high. Therefor it is good to use `1 - isect_a/union_a`, as that will give a low cost when there is a high overlap and vice versa.

**Comment by tonmoyborah** [comment]
@MuadDev Yes I agree with you, if C is the cost. However C is returned as the IoU value not the cost I think.

**Comment by tonmoyborah** [comment]
Also I think the `max_iou` set by the function `iou_matrix` function in `distances.py` is overridden by the `max_iou=0.5` supplied by the function `compare_dataframes()` in `eval_motchallenge.py` which makes the statement `C[C > max_iou] = np.nan` give errors.
I may be totally wrong but I'd find your thoughts on this very helpful.
Thank you.

**Comment by cheind** [comment]
sorry for the confusion, `iou_matrix` returns distances and not similarities. So the `1-` should be fine. @tonmoyborah will have a look at your files next week.

**Comment by tonmoyborah** [comment]
That clears up a few things for now. However I am still getting a lot of IDs while the visualization doesn't show as many. Closing this till I hit something concrete. Thank you.

**Comment by tonmoyborah** [comment]
off topic doubt: What is a RAW event?

**Comment by cheind** [comment]
The RAW events have been introduced recently and represent 1:1 copies of elements of the distance matrix in dataframe layout. They correspond to unprocessed events.

**Comment by VellalaVineethKumar** [comment]
@tonmoyborah 
Hi, I was trying to evaluate DEEP SORT using pymotmetrics, can you please let me know how to use this repo to run evaluate the results.
Do i need to add some lines in the deep sort algorithm? or is this just like the command line tool to give outputs of DEEP SORT and respective ground truth as command line arguments?

**Comment by farxaan33** [comment]
> @tonmoyborah
> Hi, I was trying to evaluate DEEP SORT using pymotmetrics, can you please let me know how to use this repo to run and evaluate the results.
> Do i need to add some lines of code in the deep sort algorithm? or is this just like the command line tool to give outputs of DEEP SORT and respective ground truth as command line arguments?

hey i was  wondering if you figured out how to generate testf files etc.

**Comment by cheind** [comment]
@tonmoyborah, @farxaan33 while off-topic in this issue, I just discovered this repo

**Comment by cheind** [comment]
@tonmoyborah, @farxaan33 while off-topic in this issue, I just discovered this repo
