### ISSUE TITLE
mostly_tracked（MT）

### ISSUE THREAD

**Issue by Wolfe233** [cheind/py-motmetrics#187]
How to obtain the percentage result of mostly_tracked?

**Comment by demuxin** [comment]
> How to obtain the percentage result of mostly_tracked?

I'm guessing that 

```
return track_ratios[track_ratios >= 0.8].count()
```

 needs to be changed to 

```
return track_ratios[track_ratios >= 0.8].count() / track_ratios.count()
```

But it still needs to be confirmed by the @cheind .

**Comment by cheind** [comment]
sounds about right!
