### ISSUE TITLE
DOI for repository (Zenodo) 

### ISSUE THREAD

**Issue by MacBlub** [cheind/py-motmetrics#197]
Dear py-motmetrics-team/contributors,

Currently I am writing a scientific paper, and intend to cite your framework specifically. Could you add an entry in Zenodo to gain a DOI for your github repository? This would make it clear for readers, where and how I computed my results.

Relevant links:
https://zenodo.org/
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Greetings

**Comment by cheind** [comment]
hey, very useful suggestion! sorry for the late reply. done -> see readme on develop
