### ISSUE TITLE
Non-ASCII character '\xc3' in file io.py

### ISSUE THREAD

**Issue by leonid-pishchulin** [cheind/py-motmetrics#2]
Hey, when running your code I get the following error
SyntaxError: Non-ASCII character '\xc3' in file ../../../py-motmetrics/motmetrics/io.py on line 19, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
 inserting "# -*- coding: utf-8 -*-" in the beginning of the io.py file helps.
could you update the repo, please?

**Comment by cheind** [comment]
Thanks for reporting. Fixed on master and develop.
