### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by mysunrise** [cheind/py-motmetrics#21]
I tried to evaluate the metric of my result. python -m motmetrics.apps.eval_motchallenge "/gt" /test"
if there are only one *.txt in /test. I can got the evaluate result quickly. however, if there are many *.txt in the folder /test, I can not the result after a long time.

**Comment by cheind** [comment]
Try leaving all but one out and see which file causes the long evaluation time.

**Comment by cheind** [comment]
Resolved? Closing in doubt. Reopen if necessary.
