### ISSUE TITLE
How to set max_iou when evaluate my MOT algorithm?

### ISSUE THREAD

**Issue by MRJTM** [cheind/py-motmetrics#22]
When I want to evaluate my MOT algorithm with py-motmetrics, I find that max_iou should be set by hand, but different max_iou will affect the result of metrics,  I don't know how to set the value of max_iou when I run the mm.distance.iou_matrix(), can anyone tell me what it should be just like the official test? 0.5 or other values?

**Comment by cheind** [comment]
0.5 is the official as far as I know. You might want to evaluate with different thresholds and generate ROC curves to see the behaviour of your algorithm as you tighten threshold towards one.

**Comment by MRJTM** [comment]
OK，thanks for replying  to me!
