### ISSUE TITLE
Mismatched ID's reporting MATCH

### ISSUE THREAD

**Issue by JakeCowton** [cheind/py-motmetrics#25]
I was plotting some of my results when I noticed a situation where for frames 0-116 `OId` 24 was matched with `HId` 3 (`Type == 'MATCH'` for all those frames), however when we get to the final frame, 117, `OId` 22 was matched with `HId` 3 (also `Type == 'MATCH'`). How can this be possible?
[acc_oid_22.xlsx](https://github.com/cheind/py-motmetrics/files/2630147/acc_oid_22.xlsx)
[acc_hid_3.xlsx](https://github.com/cheind/py-motmetrics/files/2630148/acc_hid_3.xlsx)

```
df = acc.mot_events
df.loc[HId == 3] # see attachments acc_hid_3.xlsx (last line)
df.loc[OId == 22] # See attachments acc_oid_22.xlsx (first line)
```

**Comment by cheind** [comment]
- are your hids deterministic from frame to frame? i.e has hid 3 the same meaning in all frames?
 - if so, you might get a different assignment when the total cost for a different assignment is minimal, i.e hid=3,oid=21 is still minimal in its own right, but considering the other objects/hypothesis there is better minimal total cost.

**Comment by JakeCowton** [comment]
- Yes, they're deterministic
- Not entirely sure I follow this

> if so, you might get a different assignment when the total cost for a different assignment is minimal

If `hid 3` is a tracklet of `oid 24` in frames 0-116, then in my mind, the assignment of `hid 3 to oid 22` in frame 117 must be a `SWITCH` event rather than a `MATCH` event, right? Are you saying that it's possible that a `SWITCH` event can go undetected if the distance is small enough?

**Comment by cheind** [comment]
Sorry, that's not what I wanted to say. I totally forgot about switches. So the distinction between switch and match is done here

https://github.com/cheind/py-motmetrics/blob/master/motmetrics/mot.py#L202

According to that statement, a switch is occuring if the object is already known and differs from the last hypothesis id. Additionally the time between now and the last occurence of the object has to be less or equal switch time. According to what you've mentioned this could only be the case when max switch time is set to zero.

It smells like bug. Do you have a minimal reproducible example for me?

**Comment by JakeCowton** [comment]
Ah, okay. Gotcha!

Not sure which the best way for me to represent this as an example, but I'll have a dig around over the weekend and see if I can figure out what's going on. Will hopefully be able to put a PR together. If not, I'll get a working(?) example to demo the "bug". Cheers for your help!

**Comment by cheind** [comment]
@JakeCowton any news on this?

**Comment by cheind** [comment]
I'm closing this because of lack of response. Re-open if necessary
