### ISSUE TITLE
I'm very appreciate about this code. but i have some mistakes when i want use your data to evaluate the performance. 

### ISSUE THREAD

**Issue by 404hasbeenfound** [cheind/py-motmetrics#26]
I have change the dictionary of the groundtruth data and the test data like the following format:
*/data/test/gt/gt.txt
*/data/TUD-Stadtmitte/test.txt

and i run the eval_motmetrics.py code like the following:
~/zmh/py-motmetrics-master/motmetrics/apps$ python eval_motchallenge.py /home/zs/zmh/py-motmetrics-master/motmetrics/data/test/gt /home/zs/zmh/py-motmetrics-master/motmetrics/data/TUD-Stadtmitte
 
(the former is the root routing of the file, Is it all right?)
but these is a warning like:  "WARNING - No ground truth for test, skipping."
and the "INFO - Found 0 groundtruths and 1 test files."
then, the following is the complete output words:
08:45:20 INFO - Found 0 groundtruths and 1 test files.
08:45:20 INFO - Available LAP solvers ['scipy']
08:45:20 INFO - Default LAP solver 'scipy'
08:45:20 INFO - Loading files.
08:45:21 WARNING - No ground truth for test, skipping.
08:45:21 INFO - Running metrics
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:378: RuntimeWarning: invalid value encountered in double_scalars
  return 2 * idtp / (num_objects + num_predictions)
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:370: RuntimeWarning: invalid value encountered in double_scalars
  return idtp / (idtp + idfp)
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:374: RuntimeWarning: invalid value encountered in double_scalars
  return idtp / (idtp + idfn)
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:302: RuntimeWarning: invalid value encountered in long_scalars
  return num_detections / num_objects
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:298: RuntimeWarning: invalid value encountered in long_scalars
  return num_detections / (num_false_positives + num_detections)
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:294: RuntimeWarning: invalid value encountered in long_scalars
  return 1. - (num_misses + num_switches + num_false_positives) / num_objects
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:290: RuntimeWarning: invalid value encountered in double_scalars
  return df.noraw['D'].sum() / num_detections
        IDF1  IDP  IDR Rcll Prcn GT MT PT ML FP FN IDs  FM MOTA MOTP
OVERALL nan% nan% nan% nan% nan%  0  0  0  0  0  0   0   0 nan%  nan
08:45:21 INFO - Completed

Am i do something wrong like running this code, or the data folder file cann't test this code?
Hope for your help, thanks!

**Comment by 404hasbeenfound** [comment]
i suddenly found some ideas about the routine of the file.
then i change the routine into the following format:

gtfiles:  /home/zs/zmh/py-motmetrics-master/motmetrics/apps/data/test/gt/gt.txt
tsfiles:  /home/zs/zmh/py-motmetrics-master/motmetrics/apps/data/TUD-Stadtmitte/test.txt

and the eval_motchallenge.py is the same folder with the data folder like the following format:
/home/zs/zmh/py-motmetrics-master/motmetrics/apps/data
/home/zs/zmh/py-motmetrics-master/motmetrics/apps/eval_motchallenge.py 
 
then i cd to the route of apps 
finally i run the eval_challenge.py code like this:
python eval_motchallenge.py data/test data/TUD-Stadtmitte

but the same wrong like the former:

(zmh) zs@server-bd2:~/zmh/py-motmetrics-master/motmetrics/apps$ python eval_motchallenge.py data/test data/TUD-Stadtmitte
09:50:50 INFO - Found 0 groundtruths and 1 test files.
09:50:50 INFO - Available LAP solvers ['scipy']
09:50:50 INFO - Default LAP solver 'scipy'
09:50:50 INFO - Loading files.
09:50:50 WARNING - No ground truth for test, skipping.
09:50:50 INFO - Running metrics
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:378: RuntimeWarning: invalid value encountered in double_scalars
  return 2 * idtp / (num_objects + num_predictions)
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:370: RuntimeWarning: invalid value encountered in double_scalars
  return idtp / (idtp + idfp)
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:374: RuntimeWarning: invalid value encountered in double_scalars
  return idtp / (idtp + idfn)
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:302: RuntimeWarning: invalid value encountered in long_scalars
  return num_detections / num_objects
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:298: RuntimeWarning: invalid value encountered in long_scalars
  return num_detections / (num_false_positives + num_detections)
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:294: RuntimeWarning: invalid value encountered in long_scalars
  return 1. - (num_misses + num_switches + num_false_positives) / num_objects
/home/zs/.virtualenvs/zmh/lib/python3.5/site-packages/motmetrics/metrics.py:290: RuntimeWarning: invalid value encountered in double_scalars
  return df.noraw['D'].sum() / num_detections
        IDF1  IDP  IDR Rcll Prcn GT MT PT ML FP FN IDs  FM MOTA MOTP
OVERALL nan% nan% nan% nan% nan%  0  0  0  0  0  0   0   0 nan%  nan
09:50:50 INFO - Completed

i think the structure is the same with your help's structrue like:
<GT_ROOT>/<SEQUENCE_1>/gt/gt.txt
<TEST_ROOT>/<SEQUENCE_1>.txt

Is the GT_ROOT cannot be the same with TEST_ROOT?
Should i change the GT_ROOT or the TEST_ROOT into different folder?

so i still cannot figure it out, if you have some suggestions about this question, pls reply me, thanks a lot!

**Comment by cheind** [comment]
The layout for groundtruth and test files is the following
```Layout for ground truth data
    <GT_ROOT>/<SEQUENCE_1>/gt/gt.txt
    <GT_ROOT>/<SEQUENCE_2>/gt/gt.txt
    ...
Layout for test data
    <TEST_ROOT>/<SEQUENCE_1>.txt
    <TEST_ROOT>/<SEQUENCE_2>.txt
    ...
```

where <GT_ROOT> is some directory and <TEST_ROOT> is a different one.

**Comment by 404hasbeenfound** [comment]
@cheind Wow,it's amazing for your work, i hvae download your zip file, and test the file,
i wish my mistake can help you run this code.

the structure of the gt and ts file is like this:
the gt file is like the following image:
![default](https://user-images.githubusercontent.com/37691681/49622778-dc251b80-fa05-11e8-934a-f56cefee8026.png)

and the folder ADL-Rundle-6 folder have the gt folder and the det file, then the gt file exist a gt.txt

the ts file is like the png image:
![default](https://user-images.githubusercontent.com/37691681/49622555-04604a80-fa05-11e8-98fd-99be70289180.png)

(then the gt folder have many gt folder like ADL-Rundle-6, and so on about 11 folder,  )

then i cd into my eval_motchallenge.py, then run 
python eval_motchallenge.py /home/zs/zmh/MOT/gt /home/zs/zmh/MOT/pred

finally the result will appear about 5 mins like the following words(it's a little slow but it works):

09:34:18 INFO - Found 11 groundtruths and 11 test files.
09:34:18 INFO - Available LAP solvers ['scipy']
09:34:18 INFO - Default LAP solver 'scipy'
09:34:18 INFO - Loading files.
09:34:19 INFO - Comparing KITTI-13...
09:34:19 INFO - Comparing TUD-Stadtmitte...
09:34:20 INFO - Comparing ADL-Rundle-6...
09:34:22 INFO - Comparing ETH-Pedcross2...
09:34:23 INFO - Comparing Venice-2...
09:34:26 INFO - Comparing ETH-Sunnyday...
09:34:27 INFO - Comparing KITTI-17...
09:34:27 INFO - Comparing TUD-Campus...
09:34:27 INFO - Comparing ETH-Bahnhof...
09:34:30 INFO - Comparing ADL-Rundle-8...
09:34:32 INFO - Comparing PETS09-S2L1...
09:34:35 INFO - Running metrics
watch -n 1 nvidia-smi
top
                IDF1   IDP   IDR  Rcll  Prcn  GT MT  PT  ML   FP    FN IDs   FM  MOTA  MOTP
KITTI-13       29.6% 38.8% 23.9% 28.1% 45.6%  42  0  17  25  255   548   4    5 -5.9% 0.318
TUD-Stadtmitte 64.5% 82.0% 53.1% 60.9% 94.0%  10  5   4   1   45   452   7    6 56.4% 0.346
ADL-Rundle-6   36.3% 50.0% 28.5% 42.1% 73.9%  24  1  18   5  744  2898  53   45 26.2% 0.275
ETH-Pedcross2  16.9% 61.3%  9.8% 12.2% 76.0% 133  1  17 115  240  5502  17   21  8.0% 0.301
Venice-2       35.5% 43.6% 29.9% 42.0% 61.3%  26  4  16   6 1890  4144  42   52 14.9% 0.274
ETH-Sunnyday   49.9% 83.2% 35.7% 37.1% 86.4%  30  7   4  19  108  1169   1    4 31.2% 0.240
KITTI-17       55.8% 72.2% 45.5% 52.4% 83.1%   9  1   7   1   73   325   6   10 40.8% 0.277
TUD-Campus     55.8% 73.0% 45.1% 58.2% 94.1%   8  1   6   1   13   150   7    7 52.6% 0.277
ETH-Bahnhof    54.2% 60.2% 49.3% 58.9% 72.0% 171 41  55  75 1241  2223  17   69 35.7% 0.282
ADL-Rundle-8   28.3% 33.9% 24.3% 40.1% 55.8%  28  5  13  10 2152  4064  37   45  7.8% 0.261
PETS09-S2L1    66.6% 66.6% 66.6% 91.8% 91.8%  19 18   1   0  368   367  31   37 82.9% 0.269
OVERALL        41.2% 53.2% 33.6% 45.3% 71.7% 500 84 158 258 7129 21842 222  301 26.8% 0.276
09:39:58 INFO - Completed

so you can run through it with my question. Thanks for the answer. I'll try my own test file with your code.

**Comment by 404hasbeenfound** [comment]
@cheind hi, the former question has been solved. now I have a question about the evaluation of my file with this code.
i have download the MOT challenge data, which contains the gt file. But i found that the gt file record the data with the trajectory order, but my code file record the data with the frame order.

Is that ok to use this code to evaluate my test file?
Or i should change the data into the official one?

**Comment by 404hasbeenfound** [comment]
@cheind I have test my file, but it raise some error like:


(zmh) adminroot@adminroot:~/zmh/py-motmetrics-master/motmetrics/apps$ python eval_motchallenge.py /home/adminroot/zmh/MOT16-11/gt /home/adminroot/zmh/MOT16-11/pred


05:07:58 INFO - Found 1 groundtruths and 1 test files.
05:07:58 INFO - Available LAP solvers ['scipy']
05:07:58 INFO - Default LAP solver 'scipy'
05:07:58 INFO - Loading files.
Traceback (most recent call last):
  File "eval_motchallenge.py", line 87, in <module>
    ts = OrderedDict([(os.path.splitext(Path(f).parts[-1])[0], mm.io.loadtxt(f, fmt=args.fmt)) for f in tsfiles])
  File "eval_motchallenge.py", line 87, in <listcomp>
    ts = OrderedDict([(os.path.splitext(Path(f).parts[-1])[0], mm.io.loadtxt(f, fmt=args.fmt)) for f in tsfiles])
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/io.py", line 173, in loadtxt
    return func(fname, **kwargs)
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/site-packages/motmetrics/io.py", line 64, in load_motchallenge
    engine='python'
  File "/home/adminroot/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/adminroot/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/home/adminroot/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/home/adminroot/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2266, in read
    alldata = self._rows_to_cols(content)
  File "/home/adminroot/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2909, in _rows_to_cols
    self._alert_malformed(msg, row_num + 1)
  File "/home/adminroot/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2676, in _alert_malformed
    raise ParserError(msg)
pandas.errors.ParserError: Expected 10 fields in line 1, saw 50337. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

i don't know what's wrong. Hope for your help if you know something about it. Thanks!
