### ISSUE TITLE
Nice work, but i have a unnormal parameter when i run my own data file.

### ISSUE THREAD

**Issue by 404hasbeenfound** [cheind/py-motmetrics#27]
i have been change my own file into the formal 10 parameters file.
But i have i mistake like MOTA is -82.5%, and many metrixs is 0, i'm confused about.
the output is like following:

03:52:35 INFO - Found 1 groundtruths and 1 test files.
03:52:35 INFO - Available LAP solvers ['scipy']
03:52:35 INFO - Default LAP solver 'scipy'
03:52:35 INFO - Loading files.
03:52:36 INFO - Comparing ADL-Rundle-6...
03:52:37 INFO - Running metrics
             IDF1  IDP  IDR Rcll Prcn GT MT PT ML   FP   FN IDs  FM   MOTA  MOTP
ADL-Rundle-6 0.0% 0.0% 0.0% 0.0% 0.0% 24  0  0 24 4134 5008   0   0 -82.5% 0.480
OVERALL      0.0% 0.0% 0.0% 0.0% 0.0% 24  0  0 24 4134 5008   0   0 -82.5% 0.480
03:52:40 INFO - Completed

and then i run the data file of yours,
then get a result like the following (it's like a normal one):

03:55:33 INFO - Found 11 groundtruths and 11 test files.
03:55:33 INFO - Available LAP solvers ['scipy']
03:55:33 INFO - Default LAP solver 'scipy'
03:55:33 INFO - Loading files.
03:55:34 INFO - Comparing KITTI-13...
03:55:34 INFO - Comparing PETS09-S2L1...
03:55:37 INFO - Comparing TUD-Stadtmitte...
03:55:37 INFO - Comparing Venice-2...
03:55:40 INFO - Comparing ETH-Pedcross2...
03:55:41 INFO - Comparing ADL-Rundle-8...
03:55:43 INFO - Comparing ETH-Sunnyday...
03:55:44 INFO - Comparing ETH-Bahnhof...
03:55:47 INFO - Comparing ADL-Rundle-6...
03:55:49 INFO - Comparing TUD-Campus...
03:55:49 INFO - Comparing KITTI-17...
03:55:49 INFO - Running metrics
                             IDF1   IDP   IDR  Rcll  Prcn  GT MT  PT  ML   FP    FN IDs   FM  MOTA  MOTP
KITTI-13              29.6% 38.8% 23.9% 28.1% 45.6%  42  0  17  25  255   548   4    5 -5.9% 0.318
PETS09-S2L1       66.6% 66.6% 66.6% 91.8% 91.8%  19 18   1   0  368   367  31   37 82.9% 0.269
TUD-Stadtmitte   64.5% 82.0% 53.1% 60.9% 94.0%  10  5   4   1   45   452   7    6 56.4% 0.346
Venice-2              35.5% 43.6% 29.9% 42.0% 61.3%  26  4  16   6 1890  4144  42   52 14.9% 0.274
ETH-Pedcross2    16.9% 61.3%  9.8% 12.2% 76.0% 133  1  17 115  240  5502  17   21  8.0% 0.301
ADL-Rundle-8     28.3% 33.9% 24.3% 40.1% 55.8%  28  5  13  10 2152  4064  37   45  7.8% 0.261
ETH-Sunnyday    49.9% 83.2% 35.7% 37.1% 86.4%  30  7   4  19  108  1169   1    4 31.2% 0.240
ETH-Bahnhof      54.2% 60.2% 49.3% 58.9% 72.0% 171 41  55  75 1241  2223  17   69 35.7% 0.282
ADL-Rundle-6     36.3% 50.0% 28.5% 42.1% 73.9%  24  1  18   5  744  2898  53   45 26.2% 0.275
TUD-Campus      55.8% 73.0% 45.1% 58.2% 94.1%   8  1   6   1   13   150   7    7 52.6% 0.277
KITTI-17              55.8% 72.2% 45.5% 52.4% 83.1%   9  1   7   1   73   325   6   10 40.8% 0.277
OVERALL             41.2% 53.2% 33.6% 45.3% 71.7% 500 84 158 258 7129 21842 222  301 26.8% 0.276
03:58:56 INFO - Completed

if you have some idea of this fault, pls contact me, thanks very much.
it's pretty unnormal about this, i just test one video of MOT15-2D.

**Comment by 404hasbeenfound** [comment]
and i just write the test file like:

 f.write(str(frame_index) + ','+str(track.track_id) + ',' + str(bbox[0]) + ',' + str(bbox[1]) + ',' + str(bbox[2]) + ',' + str(bbox[3]) + ',' + '1,' + '-1,'+'-1,' + '-1'+ '\n')

the first is frame_index, the second is the track_id, i think it's the same with the official version, is this ok to save and run this code?

if there is some suggestion, pls contact me, thks

**Comment by cheind** [comment]
Sorry not really sure what the problem is.

**Comment by 404hasbeenfound** [comment]
> Sorry not really sure what the problem is.

when i run the code with my file there is some parameter
is abnormal like mota is -82% and other is 0, but i run your generate file is normal, so i think there may be something wrong with my generate file, **i just wanna know how the file format is your generate file,** and my file format is """ 
f.write(str(frame_index) + ','+str(track.track_id) + ',' + str(bbox[0]) + ',' + str(bbox[1]) + ',' + str(bbox[2]) + ',' + str(bbox[3]) + ',' + '1,' + '-1,'+'-1,' + '-1'+ '\n')
"""
ths for your reply!
