### ISSUE TITLE
How to know the frame number when tracking is lost?

### ISSUE THREAD

**Issue by janhuang6** [cheind/py-motmetrics#29]
When the tracking encounters FP, FN, missed, or switches, how do we know where it happens? For instance, which frame number, tracker object ID or IDs (if switches) where it happens? Thanks!

**Comment by cheind** [comment]
you can just print the event accumulator (a pandas dataframe) `print(acc.events)`. See [here](https://github.com/cheind/py-motmetrics#populating-the-accumulator) for more usage. To filter specific events just filter the pandas dataframe using standard pandas methods.
