### ISSUE TITLE
Aggregated Metrics

### ISSUE THREAD

**Issue by tomhayat** [cheind/py-motmetrics#3]
Hello ! Thank you for your huge work ! How can you compute the aggregated metrics on the whole dataset ? It is available in the matlab eval kit. Thanks very much !!!!!

**Comment by cheind** [comment]
Hey there! What do you mean by aggregated metrics? Link?

**Comment by tomhayat** [comment]
In the motchallenge repo https://bitbucket.org/amilan/motchallenge-devkit/, there is another line in the output:
 ********************* Your 2DMOT15 Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR| GT  MT  PT  ML|   FP    FN  IDs   FM| MOTA  MOTP MOTAL 
 41.2 53.2 33.6| 45.3  71.7  1.30|500  81 161 258| 7129 21842  220  338| 26.8  72.4  27.4

**Comment by cheind** [comment]
Oh yeah, that's easily possible see the following lines

```python
import motmetrics as mm

mh = mm.metrics.create()    
accs, names = compare_dataframes(gt, ts)
    
logging.info('Running metrics')
summary = mh.compute_many(accs, names=names, metrics=mm.metrics.motchallenge_metrics)
print(mm.io.render_summary(summary, formatters=mh.formatters, namemap=mm.io.motchallenge_metric_names))
```

**Comment by ChloeEHKim** [comment]
Hi @cheind , 
Thank you for the great work. 
I'm having the same question with @tomhayat . 
In addition to the performance of individual performances of videos, can I get the overall performance as well which represent the tracker's performance? I believe the code you put above is for the individual performance of videos?

I'd like to get this
overall ->  Rcll   Prcn GT MT PT ML FP  FN IDs  FM   MOTA  MOTP
                  ~       ~      ~    ~
  in addition to
                 Rcll   Prcn GT MT PT ML FP  FN IDs  FM   MOTA  MOTP
TUD-Campus     58.22% 94.14%  8  1  6  1 13 150   7   7 52.65% 0.277
TUD-Stadtmitte 60.90% 93.99% 10  5  4  1 45 452   7   6 56.40% 0.346

Thanks

**Comment by cheind** [comment]
Oh I see - good point. There is `MetricsHost. compute_many`, but I think it does not generate a summarize row, which would be easy to add if we weight individual results by the number of frames of each clip.

**Comment by cheind** [comment]
So, I've talked to the authors of devkit and they told me that they don't do any weighting but rather concatenate the entire results into a large dataframe and the compute statistics from this large chunk. I've spent some time on implementing this. 

The `overall-summary` feature is currently tracked on this branch: 
https://github.com/cheind/py-motmetrics/tree/feature/summary

All you need to do is to enable `generate_overall=True` when calling `compute_many`. See `motmetrics/tests/test_metrics/test_motchallenge_files` for details.

Could anyone please test that this works for the files you are working on? 

-- Thanks, Chris

**Comment by ChloeEHKim** [comment]
Thank you for looking into this. I will definitely test it out today!

**Comment by cheind** [comment]
Aggregated metrics are now part of the 1.1.0 release alongside with even more features. You might also be interested that IDP, IDR and IDF1 are now part of motmetrics standard metrics.
