### ISSUE TITLE
could this code be any faster...

### ISSUE THREAD

**Issue by phoenares** [cheind/py-motmetrics#30]
.it takes more than two hours to run once

**Comment by cheind** [comment]
@phoenares try another solver, see here

https://github.com/cheind/py-motmetrics#solver-backends

**Comment by phoenares** [comment]
> @phoenares try another solver, see here
> 
> https://github.com/cheind/py-motmetrics#solver-backends

I have tried the scipy solver , it was still slow.. was it because I got too many trackers(more than 10,000) to compare? 
https://bitbucket.org/amilan/motchallenge-devkit/downloads/?tab=downloads   or maybe the matlab code is faster? thanks

**Comment by cheind** [comment]
scipy solver hasn't shown great performance in comparison. See my previous link.

**Comment by phoenares** [comment]
> scipy solver hasn't shown great performance in comparison. See my previous link.

I changed to the labjv solver, it's much faster .Thanks for your help.
