### ISSUE TITLE
accumulator.events.index.lexsort_depth == 1 causes num_fragmentations to crash

### ISSUE THREAD

**Issue by melstockman** [cheind/py-motmetrics#32]
Hello and thanks for your metrics library.
I'm trying to compute a single accumulator and running into the below error.  (I can successfully use compute_many on a list of accumulators).  I have noticed that the accumulator.events.index.lexsort_depth == 1 and that is what is causing the problem.  I could partially get rid of the error by adding ' dfo = dfo.sort_index()' in metrics.py num_fragmentations.
Any pointers to where else I can fix this?  I wasn't able to change the accumulator.events with a sort.

Thanks

------------------------------------
 File "/Users/melissa.stockman/devl/tracking/tracking/metrics/metric_calculator.py", line 116, in xcam_calculate
    summary = mh.compute(accumulator, metrics=mm.metrics.motchallenge_metrics, name=self.xcam_accum_name)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/motmetrics/metrics.py", line 142, in compute
    cache[mname] = self._compute(df_map, mname, cache, parent='summarize')            
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/motmetrics/metrics.py", line 205, in _compute
    return minfo['fnc'](df_map, *vals)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/motmetrics/metrics.py", line 284, in num_fragmentations
    diffs = dfo.loc[first:last].Type.apply(lambda x: 1 if x == 'MISS' else 0).diff()
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1478, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1866, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1511, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4107, in slice_indexer
    kind=kind)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2146, in slice_locs
    return super(MultiIndex, self).slice_locs(start, end, step, kind=kind)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4308, in slice_locs
    start_slice = self.get_slice_bound(start, 'left', kind)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2090, in get_slice_bound
    return self._partial_tup_index(label, side=side)
  File "/Users/melissa.stockman/devl/tracking/venv/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2153, in _partial_tup_index
    (len(tup), self.lexsort_depth))
pandas.errors.UnsortedIndexError: 'Key length (2) was greater than MultiIndex lexsort depth (1)'

-----------------------------------------------------------------
This is the mot_events:
----------------------------
                       Type                                   OId  HId              D
FrameId       Event                                                                  
1543358520000 2       MATCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    7232.000000
              3          FP                                   NaN    1            NaN
              6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    6782.265625
              7       MATCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5    9516.812500
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
              1      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3     576.000000
1543358520500 2      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   15049.230713
              3          FP                                   NaN    1            NaN
              6       MATCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5    3202.250000
              7      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4   18670.890625
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
              2      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    1792.265625
              3        MISS  b3f8d06a-2b00-556a-b7c2-18af9f701aca  NaN            NaN
1543358521000 2      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   17283.985407
              3          FP                                   NaN    1            NaN
              6       MATCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5    4740.765625
              7      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4   42373.250000
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
              2      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    1643.515625
              3        MISS  b3f8d06a-2b00-556a-b7c2-18af9f701aca  NaN            NaN
1543358521500 4      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    4165.015625
              5      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   54787.781907
              4      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    4  172112.900785
              5       MATCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    5   33730.562500
              6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    7913.000000
              7      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6   14436.250000
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
1543358522000 4      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    4228.515625
              5      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   14912.504390
              4       MATCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    5    9111.250000
              5      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    4  173238.706159
              6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3     439.765625
              7      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6    7941.515625
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
              2      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    7   12294.140625
              3        MISS  b3f8d06a-2b00-556a-b7c2-18af9f701aca  NaN            NaN
1543358522500 6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   59762.179383
              7      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1     754.890625
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
              6       MATCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    5   83324.265625
              7      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4   33461.546577
              8        MISS  b3f8d06a-2b00-556a-b7c2-18af9f701aca  NaN            NaN
              6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    2284.765625
              7      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6     689.520767
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
              2      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7    4906.250000
              3        MISS  59dcc018-8c9a-5c59-bb7a-e014893ca92e  NaN            NaN
1543358523000 9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    2650.062500
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   63939.023656
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    8620.140625
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5    2162.250000
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9    3227.312500
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    8986.140625
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3     350.265625
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8    2494.890625
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6     360.312500
              2      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7     137.515625
              3        MISS  59dcc018-8c9a-5c59-bb7a-e014893ca92e  NaN            NaN
1543358523500 9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    5566.140625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    2902.390625
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   81865.129200
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9    1970.312500
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5     752.515625
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4   10006.812500
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    2398.765625
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8     610.000000
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6     611.140625
              4      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11    2405.640625
              5      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7     556.562500
1543358524000 9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    7087.390625
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    2381.562500
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   71169.686046
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5     436.000000
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4   11855.886515
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9    3471.250000
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6    4186.562500
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3     928.671499
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8       2.140625
              6      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7    2416.250000
              7      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11    5301.562500
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
1543358524500 9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   33180.146638
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    3844.265625
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    3399.640625
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5    4119.062500
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4   26989.786040
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9    5434.812500
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8     120.015625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6   24139.179066
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    1340.093824
              6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11   22096.562500
              7      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7    2337.250000
              8        MISS  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8  NaN            NaN
1543358525000 9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10   12126.649307
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1   11745.390625
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2   12852.085307
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9    4026.908427
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    1854.272520
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   30328.384181
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8     433.390625
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3     114.390625
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6  188995.372394
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7   12768.390625
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11    1465.093763
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   11389.062500
1543358525500 9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1   14596.049757
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    3816.015625
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    7247.250000
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    6188.562500
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9    7767.250000
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5    6943.344437
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8     676.015625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    6  314552.173324
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3     338.312500
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7    5376.515625
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11    5557.250000
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   11892.265625
1543358526000 9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    8874.015625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1   16816.757606
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    5873.640625
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    6052.765625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   21846.672001
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9   19643.890625
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8    1676.140625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    3  837245.000000
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    6   13810.076282
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   14359.369644
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11     841.228633
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7    1707.250000
1543358526500 9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    2306.250000
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1   52993.373560
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    9109.390625
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   66346.080339
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    2439.209175
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9   29303.015625
              6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    5876.003768
              7      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8     562.500000
              8          FP                                   NaN    6            NaN
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7   40394.334813
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   11893.290199
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11    2435.515625
1543358527000 9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    2851.312500
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    6282.000000
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1   38071.482497
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    2729.140625
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9   18868.640625
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   80495.525461
              6      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8    1037.250000
              7      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    2590.518119
              8          FP                                   NaN    6            NaN
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   22332.441614
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11   19744.765625
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7   48597.128981
1543358527500 9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2     150.890625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1   27280.253014
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10    9861.015625
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   48330.988311
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9   29200.562500
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    7695.390625
              6      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8     786.812500
              7      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    6   28930.171751
              8          FP                                   NaN    3            NaN
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   16367.490597
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11   26650.000000
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7   33396.406085
1543358528000 9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    5694.577172
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10   11600.562500
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    1316.250000
              9      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9   21086.890625
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4   10261.250000
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   40387.983154
              6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    6   78400.359546
              7      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8    1465.390625
              8          FP                                   NaN    3            NaN
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11   14550.250000
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7      30.015625
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   14823.678546
1543358528500 9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    3272.312500
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10   10986.640625
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    3559.765625
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    8636.312500
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   26789.630757
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9   13384.390625
              6      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8    1599.250000
              7      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    6   16368.441221
              8          FP                                   NaN    3            NaN
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11    4369.015625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7    3080.265625
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   20190.896688
1543358529000 9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    5631.015625
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10   10114.062500
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    3367.853089
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4    3957.015625
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   31451.686585
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9   16952.562500
              6      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8     366.250000
              7      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    5295.224129
              8          FP                                   NaN    6            NaN
              9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11    3142.250000
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   22054.779926
              11     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7    1460.000000
1543358529500 9      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    2    1318.250000
              10     SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    1    4968.765625
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   10   10333.562500
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    5   35556.585153
              10     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    4     769.250000
              11     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    9   31566.312500
              6      SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e    3    1431.212951
              7      SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8    8     628.562500
              8          FP                                   NaN    6            NaN
              9      SWITCH  b3f8d06a-2b00-556a-b7c2-18af9f701aca    7     156.250000
              10     SWITCH  80bc2a54-8821-5ef7-9fd6-b48c21bdaac8   12   23850.628253
              11     SWITCH  59dcc018-8c9a-5c59-bb7a-e014893ca92e   11    2221.250000

**Comment by cheind** [comment]
Hi, could you provide a minimal example that reproduces your errors?

**Comment by melstockman** [comment]
Here's an example.  

[example.py.gz](https://github.com/cheind/py-motmetrics/files/2818746/example.py.gz)

**Comment by melstockman** [comment]
I found a smaller example which is basically the first 5 rows of data from above.  
[example-small.py.gz](https://github.com/cheind/py-motmetrics/files/2819243/example-small.py.gz)

**Comment by cheind** [comment]
Hi, I checked your sample.  What's causing the issue is that your frame ids don't vary. Changing to 

```
frameids = [1543358520000,
1543358520001,
1543358520002,
1543358520003,
1543358520004]
``` 

resolves the issue. Not sure what you are trying to accomplish. If you need to evaluate 9 ground truths and 9 hypothesis for a **single** frame, you need to pass a 9x9 distance matrix instead.

**Comment by melstockman** [comment]
Ah, I didn't realize they needed to be distinct.  I need rethink what I'm trying to do, which is get info on cross camera tracking.  Those same frame numbers are for different cameras.

thanks

**Comment by cheind** [comment]
your're welcome
