### ISSUE TITLE
Metrics across multiple cameras

### ISSUE THREAD

**Issue by melstockman** [cheind/py-motmetrics#34]
Any suggestions on how to use the metrics for checking tracking accuracy across multiple cameras?

Thanks

**Comment by melstockman** [comment]
So what I ended up doing was multiplying my timestamp (frameid) by 1000 and adding a 'camera_index'

**Comment by cheind** [comment]
seems reasonable. thanks for noting!

**Comment by TTTREE** [comment]
> 
> 
> So what I ended up doing was multiplying my timestamp (frameid) by 1000 and adding a 'camera_index'

HI，I am facing the same question. But I cannot understand you clearly. Would you please describe the method  in detail. Maybe providing the code will be better. Thanks a lot!

**Comment by melstockman** [comment]
With this metrics library, the frameid (which for me is the timestamp) must be unique.  But when there are multiple cameras, i.e. I want to do cross-camera tracking, each camera will have the same timestamp at the same time and the metrics don't work.   So in order to differentiate that frameid  field, I did this:

# Set unique frameid for xcam using timestamp plus camera index
...
frame_timestamp *= 1000
camera_index = camera_mapping[camera_name] # camera index >=0 and < 1000
frameid = frame_timestamp + camera_index
self.accumulators[name].update(ids_1, ids_2, distance_mat, frameid=frameid)

Hope that clears it up.
