### ISSUE TITLE
I have sped up for some of the components.

### ISSUE THREAD

**Issue by Helicopt** [cheind/py-motmetrics#35]
I have sped up for some of the components, for a faster combined result calculating. I have tested it in many cases, it is actually faster than the origin implement. If you want, maybe we can make a pull request.

**Comment by Helicopt** [comment]
Besides, I have added some extra functions such as skipping frames when evaluating, and add the removal step for ignoring the non-pedestrians in MOT16 gt labels (like the MATLAB processing).

**Comment by cheind** [comment]
interesting! could you highlight what you did`in more detail to improve runtime?

**Comment by Helicopt** [comment]
For example, in the original one merging step is concatenating all data and then making a larger association of all ids. Actually it is equal to some simple plus-and-divide operations, which reducing the complexity from O(N^3) to O(Sequences_number).

**Comment by Helicopt** [comment]
Also I have maked the IoU operation faster, the old one is frequently accessing pandas data and thus slower. Another modification is something like validating whether it has targets in a frame, the old one just scans from 1 to T, in some special cases maybe the first several frames contain no targets and therefore it breaks down.

**Comment by Helicopt** [comment]
I have been using the modified version for testing in the last half year, and I believe there isn't any big problems, namely bugs in my modified code, but we can refine the code or re-testing it using some data if you are going to pull the code.

**Comment by Helicopt** [comment]
Well, I have also make it compatible with MOT16/17

**Comment by cheind** [comment]
This sounds all great! Sorry for responding so late, but I'm quite busy at the moment.  This sounds like 3-4 different improvments, wow! Did you run the tests to ensure nothing has changed? Did you write some tests yourself for new features? This would easy the merging. I think best would be to merge one feature at a time (do you have independent commits?), that way the changes are manageable (from my spare time of view). What do you think?

**Comment by filipski** [comment]
I'd love to see it merged. I am trying to calculate metrics for all 11 datasets from 2DMOT2015 and motmetrics.apps.eval_motchallenge has been running for 5 hours so far and who knows how long it will take to finish... Matlab returns metrics instantly.

**Comment by cheind** [comment]
@filipski I think you could disable the global ID metrics. AFAIK they haven't been part of 2D MOT2015 but have been introduced later. Also, try another LAP solver. motmetrics has support for quite a few including one that I've written myself: https://github.com/cheind/py-lapsolver. The motmetrics Readme covers the relevant steps to change the solver backend.

**Comment by Helicopt** [comment]
Well, now I have time to do something on it. I haven't written any tests, I will try something these days. @cheind you can also tell me what you expect me to do on the merging.

**Comment by Helicopt** [comment]
I fix the former tests by this commit https://github.com/Helicopt/fast-py-MOTMetrics/commit/13d261892825f82885875c1238785af7bd68eb9e

Here I modified the compute interface to return two variables for caching results.

**Comment by cheind** [comment]
No special procedure on merging, I've been using git-flow model, so be sure to base your changes on the develop branch and submit your PR with ref to that branch.

ok very nice. What is `(df.Type == 'TRANSFER')`?

**Comment by Helicopt** [comment]
I define two extra matching states: TRANSFER and ASCEND. A TRANSFER means a hypothesis ID is assigned from an old target to a new target (the SWITCH means a target is assigned from an old hypothesis ID to a new hypothesis ID). An ASCEND means a new ID is assigned to a target (this is a sub-state for SWITCH). For instance, a->b, b->a is TRANSFER also SWITCH(not ASCEND), a->b(new) is TRANSFER but not SWITCH,   c(new)->a is SWITCH also ASCEND, but not TRANSFER.  In the origin metrics, there exists mistake cases cannot be modeled by SWITCH, but can be figured out by TRANSFER. The purpose is to make more detailed analysis.

**Comment by Helicopt** [comment]
Well, now I have added some comments in the code and the readme, and I add new test for ID_transfers and others. These non-official metrics can help the users analysize their mistakes in algorithms.

**Comment by cheind** [comment]
@Helicopt ok these seem to make sense, as inspection of results is something that needs to be improved. I would suggest one more system test: 

We should compare changes to the official devkit on MOT2015. Here's a closed issue that shows how to do this.

**Comment by Helicopt** [comment]
Where is the issue for instructions? I cannot find similar issue about MOT2015 devkit.

**Comment by cheind** [comment]
Sorry, my bad, updated my above response.

**Comment by Helicopt** [comment]
Well. I have tested it.
First case: your commit 125304fb53495de8a43f2768bf90eb932c4a87bb at branch master.
```sh
06:36:18 INFO - Found 11 groundtruths and 11 test files.
06:36:18 INFO - Available LAP solvers ['scipy']
06:36:18 INFO - Default LAP solver 'scipy'
06:36:18 INFO - Loading files.
06:36:18 INFO - Comparing Venice-2...
06:36:20 INFO - Comparing ETH-Pedcross2...
06:36:21 INFO - Comparing TUD-Campus...
06:36:21 INFO - Comparing ADL-Rundle-6...
06:36:22 INFO - Comparing KITTI-13...
06:36:23 INFO - Comparing PETS09-S2L1...
06:36:24 INFO - Comparing TUD-Stadtmitte...
06:36:25 INFO - Comparing ETH-Bahnhof...
06:36:26 INFO - Comparing ADL-Rundle-8...
06:36:28 INFO - Comparing ETH-Sunnyday...
06:36:29 INFO - Comparing KITTI-17...
06:36:29 INFO - Running metrics
                IDF1   IDP   IDR  Rcll  Prcn  GT MT  PT  ML   FP    FN IDs   FM  MOTA  MOTP
Venice-2       35.5% 43.6% 29.9% 42.0% 61.3%  26  4  16   6 1890  4144  42   52 14.9% 0.274
ETH-Pedcross2  16.9% 61.3%  9.8% 12.2% 76.0% 133  1  17 115  240  5502  17   21  8.0% 0.301
TUD-Campus     55.8% 73.0% 45.1% 58.2% 94.1%   8  1   6   1   13   150   7    7 52.6% 0.277
ADL-Rundle-6   36.3% 50.0% 28.5% 42.1% 73.9%  24  1  18   5  744  2898  53   45 26.2% 0.275
KITTI-13       29.6% 38.8% 23.9% 28.1% 45.6%  42  0  17  25  255   548   4    5 -5.9% 0.318
PETS09-S2L1    66.6% 66.6% 66.6% 91.8% 91.8%  19 18   1   0  368   367  31   37 82.9% 0.269
TUD-Stadtmitte 64.5% 82.0% 53.1% 60.9% 94.0%  10  5   4   1   45   452   7    6 56.4% 0.346
ETH-Bahnhof    54.2% 60.2% 49.3% 58.9% 72.0% 171 41  55  75 1241  2223  17   69 35.7% 0.282
ADL-Rundle-8   28.3% 33.9% 24.3% 40.1% 55.8%  28  5  13  10 2152  4064  37   45  7.8% 0.261
ETH-Sunnyday   49.9% 83.2% 35.7% 37.1% 86.4%  30  7   4  19  108  1169   1    4 31.2% 0.240
KITTI-17       55.8% 72.2% 45.5% 52.4% 83.1%   9  1   7   1   73   325   6   10 40.8% 0.277
OVERALL        41.2% 53.2% 33.6% 45.3% 71.7% 500 84 158 258 7129 21842 222  301 26.8% 0.276
06:39:41 INFO - Completed
```
Second case: my commit 36afe2b1c0cf0281548c848f252f7d6f30528f21 at branch pr.
```sh
06:38:00 INFO - Found 11 groundtruths and 11 test files.
06:38:00 INFO - Available LAP solvers ['scipy']
06:38:00 INFO - Default LAP solver 'scipy'
06:38:00 INFO - Loading files.
06:38:01 INFO - Comparing Venice-2...
06:38:02 INFO - Comparing ETH-Pedcross2...
06:38:03 INFO - Comparing TUD-Campus...
06:38:04 INFO - Comparing ADL-Rundle-6...
06:38:05 INFO - Comparing KITTI-13...
06:38:05 INFO - Comparing PETS09-S2L1...
06:38:07 INFO - Comparing TUD-Stadtmitte...
06:38:07 INFO - Comparing ETH-Bahnhof...
06:38:09 INFO - Comparing ADL-Rundle-8...
06:38:11 INFO - Comparing ETH-Sunnyday...
06:38:11 INFO - Comparing KITTI-17...
06:38:11 INFO - Running metrics
06:38:21 INFO - partials: 9.172 seconds.
06:38:21 INFO - mergeOverall: 9.173 seconds.
                IDF1   IDP   IDR  Rcll  Prcn  GT MT  PT  ML   FP    FN IDs   FM  MOTA  MOTP IDt IDa IDm
Venice-2       35.5% 43.6% 29.9% 42.0% 61.3%  26  4  16   6 1890  4144  42   52 14.9% 0.274  12  31   1
ETH-Pedcross2  16.9% 61.3%  9.8% 12.2% 76.0% 133  1  17 115  240  5502  17   21  8.0% 0.301  10  14   7
TUD-Campus     55.8% 73.0% 45.1% 58.2% 94.1%   8  1   6   1   13   150   7    7 52.6% 0.277   2   7   2
ADL-Rundle-6   36.3% 50.0% 28.5% 42.1% 73.9%  24  1  18   5  744  2898  53   45 26.2% 0.275  13  46   6
KITTI-13       29.6% 38.8% 23.9% 28.1% 45.6%  42  0  17  25  255   548   4    5 -5.9% 0.318   8   2   6
PETS09-S2L1    66.6% 66.6% 66.6% 91.8% 91.8%  19 18   1   0  368   367  31   37 82.9% 0.269   8  24   1
TUD-Stadtmitte 64.5% 82.0% 53.1% 60.9% 94.0%  10  5   4   1   45   452   7    6 56.4% 0.346   5   4   2
ETH-Bahnhof    54.2% 60.2% 49.3% 58.9% 72.0% 171 41  55  75 1241  2223  17   69 35.7% 0.282  37  14  34
ADL-Rundle-8   28.3% 33.9% 24.3% 40.1% 55.8%  28  5  13  10 2152  4064  37   45  7.8% 0.261   2  37   2
ETH-Sunnyday   49.9% 83.2% 35.7% 37.1% 86.4%  30  7   4  19  108  1169   1    4 31.2% 0.240   1   1   1
KITTI-17       55.8% 72.2% 45.5% 52.4% 83.1%   9  1   7   1   73   325   6   10 40.8% 0.277   1   6   1
OVERALL        41.2% 53.2% 33.6% 45.3% 71.7% 500 84 158 258 7129 21842 222  301 26.8% 0.276  99 186  63
06:38:21 INFO - Completed
```

We can find they are identical. My modifications have not changed the results.

However,  the results reported in motchallenge devkit is as follows:

```
Sequences: 
    'TUD-Stadtmitte'
    'TUD-Campus'
    'PETS09-S2L1'
    'ETH-Bahnhof'
    'ETH-Sunnyday'
    'ETH-Pedcross2'
    'ADL-Rundle-6'
    'ADL-Rundle-8'
    'KITTI-13'
    'KITTI-17'
    'Venice-2'

    ... TUD-Stadtmitte
TUD-Stadtmitte
 IDF1  IDP  IDR| Rcll  Prcn   FAR| GT  MT  PT  ML|   FP    FN  IDs   FM| MOTA  MOTP MOTAL 
 64.5 82.0 53.1| 60.9  94.0  0.25| 10   5   4   1|   45   452    7    6| 56.4  65.4  56.9

    ... TUD-Campus
TUD-Campus
 IDF1  IDP  IDR| Rcll  Prcn   FAR| GT  MT  PT  ML|   FP    FN  IDs   FM| MOTA  MOTP MOTAL 
 55.8 73.0 45.1| 58.2  94.1  0.18|  8   1   6   1|   13   150    7    7| 52.6  72.3  54.3

...

    ... Venice-2
Venice-2
 IDF1  IDP  IDR| Rcll  Prcn   FAR| GT  MT  PT  ML|   FP    FN  IDs   FM| MOTA  MOTP MOTAL 
 35.5 43.6 29.9| 42.0  61.3  3.15| 26   4  16   6| 1890  4144   42   52| 14.9  72.6  15.5


 ********************* Your 2DMOT15 Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR| GT  MT  PT  ML|   FP    FN  IDs   FM| MOTA  MOTP MOTAL 
 41.2 53.2 33.6| 45.3  71.7  1.30|500  81 161 258| 7129 21842  220  338| 26.8  72.4  27.4
```
We find it a little bit different in MT and IDs.  So does it matter?

**Comment by Helicopt** [comment]
We can see that my commit takes 21 secs to finish the test and the one in master branch takes 3mins and 12 secs. 

By the way, should this test be added to pytest module?

**Comment by cheind** [comment]
True it gives ```
array([[       nan,        nan,        nan],
       [0.4       , 0.42857143,        nan]])
```

Wonder where that mistake came from
