### ISSUE TITLE
Maybe a Bug

### ISSUE THREAD

**Issue by JingyuanHu** [cheind/py-motmetrics#4]
@cheind Hi, cheind. I try to import motmetrics  after I installed  it , but met a error : AttributeError: module 'importlib' has no attribute 'util' . My enveriment is Python 3.5.2. It maybe a bug . I fixed it by change `import importlib` to `import importlib   from importlib import util` in lap.py line 148. `available_solvers = [s[0] for s in solvers if util.find_spec(s[0]) is not None]` in line 162

**Comment by cheind** [comment]
Hey, I've fixed this on the develop branch. Would you mind testing the `develop` branch to see if this can be resolved?

**Comment by JingyuanHu** [comment]
Thank you for your reply. I've tested the `develop` branch. This issue is resolved.

**Comment by cheind** [comment]
ok thanks! will merge to master and push to pypi in the coming days.

JingyuanHu <notifications@github.com> schrieb am Mi., 21. März 2018 um
12:36 Uhr:

**Comment by taojake** [comment]
@soulslicer hi, i also use python2, did you have some method to resolve this?

**Comment by xiaofanglegoc** [comment]
I am also meeting this bug, after installed by python 2
