### ISSUE TITLE
Configure T, max distance which keeps association

### ISSUE THREAD

**Issue by hristo-vrigazov** [cheind/py-motmetrics#40]
After an association is made between two objects, according to the paper the association should be kept if it does not exceed a threshold `T` in the next frame. How can I configure this threshold? Based on what I have seen in the code it looks like it is just being checked if the distance is finite, which is very different from the paper. See [0], section 2.1.1, the first sentence or [2] for the original implementation and [1] for the place in the code which I think is wrong in this implementation.

[0] http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.367.6279&rep=rep1&type=pdf
[1] https://github.com/cheind/py-motmetrics/blob/master/motmetrics/mot.py#L182
[2] https://github.com/glisanti/CLEAR-MOT/blob/master/GreedyAssociation.m#L40

**Comment by cheind** [comment]
Let me clarify. In py-motmetrics the threshold you mention to keep associations alive is not part of motmetrics itself. It is part of the given distance matrix. All elements that cannot pair are signalled with NAN. 

What py-motmetrics does, it allows you to compute distances between hypothesis of your tracker and ground truths of the current frame. It then prevents potential pairings (of established or new tracks) that exceed a given threshold (by indication with NAN in the input distance matrix). 

So, [0] 2.1.1 states
> First of all, the correspondence between an object oi and
a hypothesis hj should **not** be made if their distance disti,j
exceeds a certain threshold T.

This statement does not relate to tracks already established.

In [2] it seems like a greedy assignment algorithm is used on the principle of first-come-first-serve. In contrast py-motmetrics assigns the  **remaining** possible pairs to matches, misses and switches using a per-frame optimal algorithm based on minimum costs (LAP). Where **remaining** refers to all potential pairs, **after** already established ones have been continued.

Re-establish:
https://github.com/cheind/py-motmetrics/blob/master/motmetrics/mot.py#L171

Assign remainings:
https://github.com/cheind/py-motmetrics/blob/master/motmetrics/mot.py#L190

Does this clear up things for you?

**Comment by hristo-vrigazov** [comment]
Mmm I see, so it is something which has to be done before we fill in the distance matrix. Also, I realized I completely misunderstood 2.1.1 in the paper, sorry about that :D

**Comment by cheind** [comment]
Correct. You are welcome, I had to look it up too!  ;)
