### ISSUE TITLE
Can this repo be used to evaluate detector performance?

### ISSUE THREAD

**Issue by ZongweiZhou1** [cheind/py-motmetrics#42]
This repo is a great job. And I can embed it into my muti-target tracking framework. Now I want to use my private detector, so I wonder is this repo can be used to evaluate detectors for multi-target detection?  Like the metric `MODA, MODP` and so on

**Comment by cheind** [comment]
do you have any references for MODA and MODP, or are you confusing them with  MOTA and MOTP (the latter ones are supported by motmetrics), see Readme.md in the main directory.

**Comment by ZongweiZhou1** [comment]
Oh， I mean the CLEAR metric used for evaluation detection in MOT, ref the website [https://motchallenge.net/results/MOT17Det/](https://motchallenge.net/results/MOT17Det/)

**Comment by cheind** [comment]
These metrics are currently not part of motmetrics. However from [1](https://cvhci.anthropomatik.kit.edu/~stiefel/papers/clearOver2006-11-7.pdf) I think it should be quite easy to add by reusing [existing metrics](https://github.com/cheind/py-motmetrics/blob/develop/motmetrics/metrics.py). Happy to accept a PR.

Best,
Christoph

**Comment by mmaaz60** [comment]
Hi, are the metrics for calculating detector accuracy added?

**Comment by Sentient07** [comment]
Hello, 

I am interested in these metrics as well. I don't find their definition in the original CLEAR MOT paper, but I do find it here : https://catalog.ldc.upenn.edu/docs/LDC2011V03/ClearEval_Protocol_v5.pdf (section 12.1.1, 12.1.2). If you're still interested, I can send a PR with this implementation. 

Regards,
Raman

**Comment by Sentient07** [comment]
Hello,

I am interested in these metrics as well. I don't find their definition in the original CLEAR MOT paper, but I do find it here : https://catalog.ldc.upenn.edu/docs/LDC2011V03/ClearEval_Protocol_v5.pdf (section 12.1.1, 12.1.2). If you're still interested, I can send a PR with this implementation.

Regards,

**Comment by cheind** [comment]
In my view, support for detection would be very welcome. @jvlmdr do you have experience with such metrics or which one we should prefer?
