### ISSUE TITLE
Reference Results

### ISSUE THREAD

**Issue by ronshpindler** [cheind/py-motmetrics#43]
Hi,

I am trying to understand the results meaning.
I have compared one tracking ground truth file with itself and got the following:
           IDF1   IDP    IDR   Rcll  Prcn GT MT PT ML   FP FN IDs  FM  MOTA  MOTP
CVPR19-01 86.2% 75.8% 100.0% 100.0% 75.8% 74 74  0  0 6349  0   0   0 68.0% 0.000
OVERALL   86.2% 75.8% 100.0% 100.0% 75.8% 74 74  0  0 6349  0   0   0 68.0% 0.000

Shouldn't the MOTA and MOTP be 100%?
Shouldn't the Prcn be 100%?

**Comment by cheind** [comment]
Interesting...
For MOTP see [here](https://github.com/cheind/py-motmetrics#motchallenge-compatibility).  That's fine.

For the others I have to speculate. How did you compute the distance between objects / hypotheses? The only way we get less tha 100% for these two metrics is that we have false positives, ie. hypothesis that couldn't be matched to any object id. This happens for example if the distance between such pairs is   NaN.

**Comment by ronshpindler** [comment]
Thanks Cristoph for the fast replay.

I got the results by running eval_motchallenge.py on the first ground truth file of the training samples (CVPR19-01\gt\gt.txt) against itself (simply duplicated it and saved the copy as CVPR19-01.txt).
I expected the results of those parameters to be 100%...

**Comment by cheind** [comment]
Could you share the file?  If you look into the test `test_motchallenge_files` and change to  
```
def test_motchallenge_files_regression():
    dnames = [
        'TUD-Campus',
        'TUD-Stadtmitte',
    ]
    
    def compute_motchallenge(dname):
        df_gt = mm.io.loadtxt(os.path.join(dname,'test.txt'))
        df_test = mm.io.loadtxt(os.path.join(dname,'test.txt'))
        return mm.utils.compare_to_groundtruth(df_gt, df_test, 'iou', distth=0.5)

    accs = [compute_motchallenge(os.path.join(DATA_DIR, d)) for d in dnames]

    # For testing
    # [a.events.to_pickle(n) for (a,n) in zip(accs, dnames)]

    mh = mm.metrics.create()
    summary = mh.compute_many(accs, metrics=mm.metrics.motchallenge_metrics, names=dnames, generate_overall=True)

    print()
    print(mm.io.render_summary(summary, namemap=mm.io.motchallenge_metric_names, formatters=mh.formatters))
    # assert ((summary['num_transfer'] - summary['num_migrate']) == (summary['num_switches'] - summary['num_ascend'])).all() # False assertion
    summary = summary[mm.metrics.motchallenge_metrics[:15]]
    print(summary)
```

then run with `pytest -k test_motchallenge_files_regression -s`. The output will be as expected.
