### ISSUE TITLE
I have some questions about the source code, in mot.py and metrics.py

### ISSUE THREAD

**Issue by ArchNew** [cheind/py-motmetrics#44]
## In `mot.py`
there is a piece of code as follows:
```python
# 1. Try to re-establish tracks from previous correspondences
for i in range(oids.shape[0]):
    if not oids[i] in self.m: # only consider objects that have been tracked
        continue

    hprev = self.m[oids[i]]  
    j, = np.where(hids==hprev)  
    if j.shape[0] == 0:  
        continue
    j = j[0]  

    if not dists[i, j] == INVDIST:
        oids[i] = ma.masked
        hids[j] = ma.masked
        self.m[oids.data[i]] = hids.data[j] # ?? is this really necessary?
        self.events.loc[(frameid, next(eid)), :] = ['MATCH', oids.data[i], hids.data[j], dists[i, j]]
```
the second to the last line, I don't think this assignment is necessary. Isn't it the same pair in the previous frame? In my humble opinion, there's no need for this assignment.

## In `metrics.py`
the `_compute()` function
```python
def _compute(self, df, name, cache, parent=None):
    """Compute metric and resolve dependencies."""
    assert name in self.metrics, 'Cannot find metric {} required by {}.'.format(name, parent)
    minfo = self.metrics[name]
    vals = []
    for depname in minfo['deps']:
        v = cache.get(depname, None)  
        if v is None:  
            v = cache[depname] = self._compute(df, depname, cache, parent=name)
        vals.append(v)
    return minfo['fnc'](df, *vals)
```
the parameter `parent` serves no function here.

I don't know if my opinion is right or I miss something. Please shed some light on those two parts.

**Comment by cheind** [comment]
Concerning the first issue: It seems like the assignment is unnecessary. As far as the second issue is concerned, it at least in an informative way here `assert name in self.metrics, 'Cannot find metric {} required by {}.'.format(name, parent)`

**Comment by cheind** [comment]
Closing this issue due to the lack of activity.
