### ISSUE TITLE
Why the MOTA and IDF1 are not 100% when I input the ground truth as the tracking results?

### ISSUE THREAD

**Issue by Reeshark** [cheind/py-motmetrics#48]
Why the MOTA and IDF1 are not 100% when I input the ground truth as the tracking results? For example your data MOT16-13, which MOTA is only 31.8 and IDF1 is only 74.6?

**Comment by cheind** [comment]
this is related to #45

**Comment by Reeshark** [comment]
> this is related to #45

Maybe the ground truth concludes some non-person bounding boxes such as bicycle, car, occlusion. But these boxes in ground truth are removed previously. So these bbox belong to False Positive. Do you think this explanation is correct?

**Comment by huhuman** [comment]
I found that if we only keep those observations with Label ID=1 (Pedestrian) in ground truth, the output would be what we expected.
![image](https://user-images.githubusercontent.com/20295053/66286135-99bcbb80-e902-11e9-8401-a448cd2e2fc5.png)
I have no idea that should mot evaluation ignore all other boxes?

**Comment by abhaygargab** [comment]
Can somebody please explain the reason why this is happening? Why should we keep only Label ID=1, when all other IDs also belong to pedestrians? If other IDs belong to some other classes then they should not be in included in det.txt and gt.txt.
Am i missing something, or this is still an unsolved bug?

Thank You

**Comment by jvlmdr** [comment]
The other IDs belong to some other classes. They should not be included in det.txt but they are included in gt.txt.
