### ISSUE TITLE
Crash on all empty hypotheses in accumulator

### ISSUE THREAD

**Issue by jirip** [cheind/py-motmetrics#49]
Hello, this is somehow edge case (maybe similar to #23). I run motmetrics evaluation on a set of experiments and it happens that there are no hypotheses at all. Something like this:
```
acc = motmetrics.MOTAccumulator(auto_id=True)
acc.update([2], [], numpy.empty((0, 0)))
acc.update([2, 3], [], numpy.empty((0, 0)))
acc.update([3], [], numpy.empty((0, 0)))

metrics = motmetrics.metrics.create()
summary = metrics.compute(acc)
```
That will cause a crash on `motmetrics.py:L377`:
```
IndexError: cannot do a non-empty take from an empty axes.
```
I'd expect to get results like:
frames: 3 , mostly_lost: 2, num_misses: 4, mota: 0, motp: nan, ...

**Comment by Borda** [comment]
@cheind @christosavg what id the expected behaviour in such a case?

**Comment by cheind** [comment]
That should be fixed on develop. Closing this. Reopen if necessary.
