### ISSUE TITLE
Interpreting data fields in MOT Benchmark, ground truth data

### ISSUE THREAD

**Issue by rishabh700** [cheind/py-motmetrics#50]
Hi, Thank you for this repo. Great work!

I am facing some difficulties in understanding the ground-truth data. So, I have downloaded the ground truth data from the [MOT challenge_2015.](https://motchallenge.net/data/2D_MOT_2015/). I have understood the first six columns of the dataset but unable to do so for the rest four columns. Following is the sample data from the directory <\2DMOT2015\train\ETH-Bahnhof\gt>:

_frame no., object_id, bb_left, bb_top, bb_width ,bb_height,_ **(?), (?), (?), (?)**
_1, 1, 212, 204, 20, 57,_ **0, -3.1784, 16.34, 0.45739**
_1, 2, 223, 181, 36,104,_ **1, -1.407, 9.0212, 0.68774**

Such data fields in the ground truth data exist for videos ETH-Bahnhof, ETH-Sunnyday, PETS09-S2L1 and TUD-Stadtmitte. As for the other videos in the 2DMOT2015 dataset, they are in the standard format with last four values as -1.

**Comment by bmetge** [comment]
Column 7 relates to the confidence. Columns 8 to 10 are used only for 3D MOT Challenge, so in your case , you can put them to -1. You check for details: [here](https://motchallenge.net/)

**Comment by rishabh700** [comment]
Thanks for your reply @bmetge
