### ISSUE TITLE
Hello,I have a question I would like to ask you, how to calculate Hz or runtime?

### ISSUE THREAD

**Issue by gyc521zsc** [cheind/py-motmetrics#56]
![image](https://user-images.githubusercontent.com/50411057/67769433-70b9c180-fa8f-11e9-8faa-2b1a66c6a725.png)

**Comment by cheind** [comment]
Hi, the runtime refers to the execution time of the respective algorithm. Since motmetrics usually works on pre-computed data from algorithms, motmetrics cannot compute runtimes. I think the authors timed the algorithms independently of computing the other metrics.

**Comment by cheind** [comment]
-
