### ISSUE TITLE
Does this evaluation code support properly ignore those should be treated as "do not care"?

### ISSUE THREAD

**Issue by DianJin2018** [cheind/py-motmetrics#68]
Hi, firstly thanks for your code.I have done some evaluation with this code on my own datasets, but there are some inconsistent in the results compared to another evaluation website that I submitted to, so I try to check out the reasons.After some analysis I get some reasonable suspicion. To say it in short, there is a description in the mot16 paper that says:
![image](https://user-images.githubusercontent.com/40662174/72436494-819ae900-37db-11ea-8b79-463313862ab9.png)
Just as it describes, there are some rows in the gt that should be specially treated as it can not be simply treated as positive or negative samples. And there are also some similar instance in my datasets that is labelled as "do not care".So I check out this code and find that in the loading pharse it seems that these lines are simply removed when loading label file, in this case when a tracker detect those instances and write it to the result files, it will be considered as false postive.  I do not go deep into this code yet, I wonder if these lines are just simply removed?
`# Remove all rows without sufficient confidence`
`return df[df['Confidence'] >= min_confidence]`

**Comment by cheind** [comment]
I'm not sure if I understand your question correctly. But if you care about pre-processing files according to MOT16/17 ground truths, I think there has been a pull request living on the develop branch that fixes this issue

https://github.com/cheind/py-motmetrics/blob/develop/motmetrics/apps/evaluateTracking.py

**Comment by DianJin2018** [comment]
@cheind I check the pull request and do not find any specially description about my question. I shall illustrate my question in detail.
Taking a seuqence in mot16 for example.
Firstly,  as shown below there are some reflection of pedestrian in the mirror , and it's labelled as class 12 in the gt file just as described in the mot paper. However just as the paper described it should not just be ignored and should in a sence be considered as a hard exmaple because it‘s still a kind of pedestrian and sometimes a detector can still detect it and write it to the result file , but it should not be considered as a mistake. To be more specific, missing it should not be considered as false negative and detecting it should not be considered as false postivate when evaluating.

![ped](https://user-images.githubusercontent.com/40662174/72508987-9f228e00-3881-11ea-8755-f2239e27ca50.jpg)


![image](https://user-images.githubusercontent.com/40662174/72503532-e8211500-3876-11ea-9043-72cd490b2413.png)

I have done a simple test with this code.
Test1
- use the downloaded MOT16-09 gt file  as gt.
- keep all the rows in gt file that are labeled as class 1 and 12 as result file.
here is the result, obviously class 12 in result file are considered as false positive

![image](https://user-images.githubusercontent.com/40662174/72504615-1dc6fd80-3879-11ea-979e-6819434c3932.png)
Test2
- use the download MOT16-09 gt file as gt but modify the confidence score of class 12 to 1(so that it will not simply be removed in the loading pharse)
- keep all the rows in gt file that are labeled as class 1 as result file.
here is the result ,obviously missing class 12 in the result file are considered as false negative.
![image](https://user-images.githubusercontent.com/40662174/72505189-63d09100-387a-11ea-8211-74abb1065ffd.png)
I don't konw if  I made myself clear, hope you can help me with it.

**Comment by DianJin2018** [comment]
@cheind Sorry, I check the develop branch in detail now and find that it alreay resolve my question, I suppose this issue can be closed now.

**Comment by cheind** [comment]
Great, thanks!
