### ISSUE TITLE
Testing on different classes

### ISSUE THREAD

**Issue by tiberium24** [cheind/py-motmetrics#69]
Hello,

Thank you for your great work.

I would like to test on a car tracking dataset. Do I just change ground truth and detection files as:
**ground truth**: frame objectID xmin ymin width height 1 -1 -1 -1 
**test results**: frame objectID xmin ymin width height -1 -1 -1 -1 

Does it make sense to run `motmetrics.apps.eval_motchallenge` on those files for cars?

**Comment by cheind** [comment]
yes, that seems reasonable to me. MOT layout is as follows
```'FrameId', 'Id', 'X', 'Y', 'Width', 'Height', 'Confidence', 'ClassId', 'Visibility', 'unused'```

Note that the [parser](https://github.com/cheind/py-motmetrics/blob/develop/motmetrics/io.py#L83) assumes matlab convention where image locations start at (1,1) instead of (0,0).

**Comment by tiberium24** [comment]
Thanks a lot! And for your quick response!
