### ISSUE TITLE
Using metrics with custom detections

### ISSUE THREAD

**Issue by arturioxas** [cheind/py-motmetrics#7]
Hello, I have built tracker using YOLO+SORT and I would like to evaluate its performance against benchmark. Is your code going to work with detection I made using YOLO detector?

**Comment by cheind** [comment]
Hi, I haven't used motmetrics for benchmarking detections. I'm mostly interested in tracking. That said, it should be possible to benchmark detections. You will need to
 - make sure every gt object has a unique id in every frame
 - disable a couple of metrics that perform tracking (or it will take forever to compute). Go with an empty set of metrics first and start adding metrics you require.
