### ISSUE TITLE
Q: new Release

### ISSUE THREAD

**Issue by Borda** [cheind/py-motmetrics#73]
First of all, Thanks for this very useful package. I have noticed that there is steady development on `develop` branch, the `master` is quite behind and also pip release is from mid-2018... I was wondering whether you plan a release with last changes? :]

**Comment by cheind** [comment]
I planned todo so before Xmas last year, but didn't find the time todo so.

**Comment by Borda** [comment]
btw, I was running the last release on our case of 100k timestamps and it took about 370s, compared to running actual develop version which elapsed in 24s, so I am really looking forward to seeing the new release soon... :rocket:

**Comment by cheind** [comment]
Yes me too. I'm terribly sorry I can't act faster. I hope that I can release next week. @jvlmdr any pending things from your side? Otherwise I will try to release from develop next week. I suggest v1.2.

**Comment by jvlmdr** [comment]
Yep. I will try to make a short list of things to do before the release and we can discuss. Aiming for next week sounds good!

**Comment by jvlmdr** [comment]
@Borda Would you be OK with sending us some real data (ground-truth and predictions) for a day-long sequence with 100k+ frames? It would be useful for benchmarking.

**Comment by Borda** [comment]
I may share it via mail, do not want to put it public... 8-)

**Comment by jvlmdr** [comment]
Haha of course, no problem. If you're happy to send it to me (and I will keep it private), then use jack.valmadre@gmail.com

**Comment by jvlmdr** [comment]
FYI I tried out the `solvers` branch using the accumulator that you provided and I got some further improvement in speed (this is the cumulative time for `lap.py:69(minimum_weight_matching)` according to `cProfile`)

| solver    | cumtime |
|-----------|---------|
| lapmod    | 0.025   |
| ortools   | 0.105   |
| lap       | 5.166   |
| lapsolver | 6.555   |

However, this is still relatively small (20%) compared to the total processing time of 24 sec on your system.

**Comment by jvlmdr** [comment]
Wow actually.. scipy updated its implementation of `linear_sum_assignment` in v1.4
https://scipy.github.io/devdocs/release.1.4.0.html#scipy-optimize-improvements

| solver      | cumtime |
|-------------|---------|
| scipy (1.3) | 61.404  |
| scipy (1.4) | 0.120   |

**Comment by cheind** [comment]
an update for everyone around. If everything goes well, py-motmetrics 1.2 will be available tomorrow.

**Comment by Borda** [comment]
https://github.com/cheind/py-motmetrics/releases/tag/v1.2
