### ISSUE TITLE
Update author/copyrights

### ISSUE THREAD

**Issue by cheind** [cheind/py-motmetrics#81]
@jvlmdr I've added you as an author! I've updated only `setup.py`, `ReadMe.md` and `License` so far. I think we should also update the copyright fields in each file, in case we intend to stick with that formatting in the future.

**Comment by jvlmdr** [comment]
Awesome! Thanks :)

**Comment by jvlmdr** [comment]
Done in PR https://github.com/cheind/py-motmetrics/pull/85
