### ISSUE TITLE
Changing the default branch

### ISSUE THREAD

**Issue by cheind** [cheind/py-motmetrics#83]
I think we should change the [default branch](https://stackoverflow.com/questions/14972170/how-to-view-github-contributors-graph-for-branches-other-than-master) to `develop`, so that pull-requests by default are based on that branch. Any objections?

**Comment by jvlmdr** [comment]
Sounds good. Everyone submits pull requests to master the first time, myself included ;)

**Comment by cheind** [comment]
ok, done. insights/metrics/contributions are now also displayed according to the develop branch.
