### ISSUE TITLE
PyPi - Content of Readme.md should be project description.

### ISSUE THREAD

**Issue by cheind** [cheind/py-motmetrics#86]

**Comment by jvlmdr** [comment]
Looks like we can do it using this method:
https://github.com/di/markdown-description-example/blob/master/setup.py

Can we amend the release or would it have to be v1.2.1 already? :)

**Comment by cheind** [comment]
AFAIK in gitflow a hotfix on master should lead to a minor version increment. But I guess, for a hotfix this is not urgent enough (since the github page is linked anyways).

**Comment by jvlmdr** [comment]
Updated `setup.py` to do this for the next release (I'm not sure how to test it though, i.e. what will happen to links and images)

**Comment by cheind** [comment]
I think that should be quite easy using [TestPyPi](https://packaging.python.org/guides/using-testpypi/), which works nicely with twine (the upload tool used in appveyor py-motmetrics). Unfortunately we have currently only upload when ` if ($env:APPVEYOR_REPO_BRANCH -eq "master")`. How about changing the else clause to upload to the test server (always)?

**Comment by jvlmdr** [comment]
Sounds good. I'm not sure exactly how the deployment to PyPI works and I don't want to accidentally trigger a release so I'll let you make the modification ;)

**Comment by cheind** [comment]
So, I've recreate the user on pypi-test and adapted appveyor.yaml db0236bb12dc4f63ca5f4bd6be6c61517f4b6f73. Let's see what happens.

**Comment by cheind** [comment]
One issue that I see is that we are using `--skip-existing` in twine, so that twine does not fail when a package already exists on pypi. That's fine for the master where we increase version numbers as we trigger twine, however for the develop branch we are not necessarily doing so. Using `--skip-existing` will not upload the conflicting package

**Comment by cheind** [comment]
Here's the result
https://test.pypi.org/project/motmetrics/1.2.0/

Looking good.

**Comment by cheind** [comment]
Interesting, [this build](https://ci.appveyor.com/project/cheind/py-motmetrics/build/job/f8g5v2g7ks32wmdi) fails with error `HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://test.pypi.org/help/#description-content-type for more information. for url: https://test.pypi.org/legacy/` which seems to be related to our long_description content.

**Comment by cheind** [comment]
see https://test.pypi.org/help/#description-content-type

**Comment by cheind** [comment]
oh, this seems to be related to 
https://github.com/pypa/warehouse/issues/5855

and may be caused by an incompatible setuptools on some platforms :(

**Comment by cheind** [comment]
in python 
3.5 : setuptools-45.1.0-py3-none-any.whl | build fails
3.6: setuptools-45.1.0.post20200127 | build ok

maybe that's causing the trouble?

**Comment by cheind** [comment]
@jvlmdr would you mind quickly reverting the readme.md changes to setup.py? I've deleted the release on pypitest, so that we can check if if builds again

**Comment by jvlmdr** [comment]
Done

**Comment by cheind** [comment]
Thanks, may have a look at it tonight. Primarily, I'd like to have #87 in place first.

**Comment by cheind** [comment]
#87 is now resolved. See for example [this build](https://ci.appveyor.com/project/cheind/py-motmetrics/build/job/1r9w6xl1evd8a2jl) which created [this pre-release](https://test.pypi.org/project/motmetrics/1.2.0.dev138/) with version `1.2.0.dev138`. Meaning that each development build now pushes its own release to pypi-test. Hopefully, this helps in debugging the current issue.

**Comment by jvlmdr** [comment]
This is great!

**Comment by jvlmdr** [comment]
It seems like the python 3.6 environment uses `twine-3.1.1` whereas the python 3.5 environment uses `twine-1.15.0`. This could be the cause.
python 3.6 log: https://ci.appveyor.com/project/cheind/py-motmetrics/builds/30610524/job/u66v9iy2q6v192sw
python 3.5 log: https://ci.appveyor.com/project/cheind/py-motmetrics/builds/30610524/job/o5k75flnrmetfco5

**Comment by cheind** [comment]
that's strange. According to https://pypi.org/project/twine/#files 3.1.1 shoul dbe available for both python versions. We are also updating `pip` before upgrading twine.

**Comment by cheind** [comment]
This can be reproduced locally using miniconda as follows 
```conda create -n twinetest python=3.5 pip
conda activate twinetest
pippython -m pip install -U pip
Collecting pip
python -m pip install -U pip
pip install --upgrade twine
> Collecting twine
> Downloading twine-1.15.0-py2.py3-none-any.whl (35 kB)```

**Comment by cheind** [comment]
mybad, according to https://pypi.org/project/twine/#files only python >= 3.6 is required. 3.5 support seems to be dropped.

**Comment by jvlmdr** [comment]
OK. Should we just drop python 3.5 from appveyor?

**Comment by cheind** [comment]
I think that would be fine, since we don't actually build any binaries and distribute only source wheels. 
Alternatively, we could skip twine unless `$env:PYTHON_VERSION` is 
`3.6`. That way we would still test motmetrics with python 3.5.

I'll try that. Also, should we add Python 2.7/3.7/3.8 into test pool?

**Comment by jvlmdr** [comment]
OK, either is fine by me.

Yep sure, let's add them.

**Comment by jvlmdr** [comment]
Cool, the `long_description` seems to be working now!

**Comment by cheind** [comment]
kewl! moving CI support for Python 2.7/3.7/3.8 to a new issue.
