### ISSUE TITLE
Reduce AppVeyor CI warning outputs 

### ISSUE THREAD

**Issue by cheind** [cheind/py-motmetrics#88]
Tons of error/warning messages related to installing pandas. See for example [this](https://ci.appveyor.com/project/cheind/py-motmetrics/build/job/j84152736i7hp6yg?fullLog=true) log.

**Comment by jvlmdr** [comment]
I think I fixed this in https://github.com/cheind/py-motmetrics/commit/618245f5eec9339da5c1576a48c1751d36bcf488

See log: https://ci.appveyor.com/project/cheind/py-motmetrics/builds/30609924/job/094c4plgwn3kogeb
