### ISSUE TITLE
No ground truth for test when i use the TUD-Campus data to test

### ISSUE THREAD

**Issue by yuehui130** [cheind/py-motmetrics#93]
How can i use the TUD-Campus data to test the evalution.But something is wrong.
log found the 1 groundtruths and 1 test,but then there is no ground truth for test.
![1$V%_OL3(3LRC)R~3S0RY(V](https://user-images.githubusercontent.com/57430945/75233650-88664400-57fc-11ea-875d-035e0467c14a.png)

and I change the eval_motchallenge.py code to 
![%CJ A_NW58)YUW1RS BCFE8](https://user-images.githubusercontent.com/57430945/75233863-e4c96380-57fc-11ea-982b-d392048e25ef.png)

Could u tell me where is the problem and how to solve the problem？

**Comment by yuehui130** [comment]
Such a question has already been asked, I searched for 'no groundtruths for test' and found the answer.

**Comment by cheind** [comment]
thanks for figuring this out!
