### ISSUE TITLE
Compute MOTA per frame?

### ISSUE THREAD

**Issue by niraj-bhujel** [cheind/py-motmetrics#97]
Hello, is there a way to get MOTA and other metrics values at each frame of a sequence?

**Comment by cheind** [comment]
Sorry, I missed your question. No, that functionality is not directly implemented. Are you refering to commulative values or seperate values for each frame. I doubt that the latter makes sense for many metrics.

**Comment by cheind** [comment]
I close this problem as solved. If not, feel free to reopen.
